### ISSUE TITLE
Bug when using height: 'fit' and filtering

### ISSUE THREAD

**Issue by g2petter** [FancyGrid/FancyGrid#1]
When the height is set to 'fit', the table grid gets resized too much when filtering. The attached screenshots illustrate what happens when using the  example from the documentation and searching companies for "siemens"

The results are still there (verified by using the Chrome developer tools) but they're hidden below the bottom of the table.
![image](https://cloud.githubusercontent.com/assets/5946832/24745337/a3726ada-1ab5-11e7-902a-2ffdd6fed2a2.png)
![image](https://cloud.githubusercontent.com/assets/5946832/24745346/aee2750e-1ab5-11e7-9230-4f3a451cbbf8.png)

**Comment by MikhailTatsky** [comment]
Thank you for the report.
It was added in bug tracker.

**Comment by MikhailTatsky** [comment]
It was fixed.
Please try again with latest version 1.5.11

**Comment by g2petter** [comment]
I retried it now, and it doesn't seem to work.

I'm using the latest minified code from cdn.fancygrid.com

It looks like the height property of the fancy-grid-1 div isn't being set to the correct value. If I manually adjust that the search result becomes visible.

![image](https://cloud.githubusercontent.com/assets/5946832/24897311/c7c37e2e-1e98-11e7-9bd3-c1cee098600d.png)
![image](https://cloud.githubusercontent.com/assets/5946832/24897331/d4f22b4a-1e98-11e7-8cb3-c0acfc7b9616.png)

**Comment by MikhailTatsky** [comment]
Please try to clear cache
CTRL + F5
And check in console that Fancy.version is 1.5.11

**Comment by g2petter** [comment]
1.5.11 confirmed: 

![image](https://cloud.githubusercontent.com/assets/5946832/24897972/5381af06-1e9b-11e7-9606-97226379b325.png)

**Comment by MikhailTatsky** [comment]
Hmmm,

Thank you for the report.

**Comment by MikhailTatsky** [comment]
Please try again. Version is 1.5.12
If bug still exists than provide us sample case and information about OS, browser version.

P.S.:
We improved working with fit, but can not replicate bug in 1.5.11

**Comment by g2petter** [comment]
It works in 1.5.12 now. Thanks for helping out!

**Comment by MikhailTatsky** [comment]
Good :)
