### ISSUE TITLE
Problem with 2 action columns callback by one event cellclick

### ISSUE THREAD

**Issue by dreaming1402** [FancyGrid/FancyGrid#10]
Hello,
I have problem with fancygrid have 2 action columns type, I can't discern 2 action columns by one event cellclick or another event, When I set the 'index' option, I get 'undefined' in cell data. It working not fine like someone type: string, date, checkbox...

**Comment by MikhailTatsky** [comment]
Could please add screenshot/screencast and part of code?
A bit not clear what exactly works wrong.

**Comment by dreaming1402** [comment]
"When I set the 'index' option, I get 'undefined' in cell data" -> [http://prntscr.com/fwkuwf](http://prntscr.com/fwkuwf)
this is my code: 
                        `columns: [{
                                type: 'order',
                                title: 'No.',
                                locked: true,
                                width: 40
                            }, {
                                type: 'action',
                                title: 'Tải',
                                width: 40,
                                locked: true,
                                filter: false,
                                value: '',
                                items: [{
                                    text: '<i class="fa fa-download"></i>',
                                    cls: 'action-print_card',
                                    action: 'cellclick'
                                }]
                            }, {
                                type: 'action',
                                title: 'Xem',
                                index: 'action_view',
                                width: 40,
                                locked: true,
                                filter: false,
                                value: '',
                                items: [{
                                    text: '<i class="fa fa-eye"></i>',
                                    cls: 'action-print_card',
                                    action: 'cellclick'
                                }]
                            }, {
                                type: 'combo',
                                index: 'employee_department',
                                title: 'Bộ phận',
                                width: 100,
                                locked: true,
                                displayKey: 'employee_department',
                                data: {
                                    proxy: {
                                        url: '?c=Employee&a=getPrintList&i=employee_department'
                                    }
                                }
                            },]`

**Comment by MikhailTatsky** [comment]
About index for action column.
For action column type it is not possible to use index.

You can try to mix rendered and controllers
Here is sample
http://jsfiddle.net/gh/get/jquery/1.9.1/FancyGrid/FancyGrid-Samples/tree/master/jsfiddle/grid/events/controllers
