### ISSUE TITLE
Server request flood when using stateful option

### ISSUE THREAD

**Issue by gspfranc** [FancyGrid/FancyGrid#100]
Hi,
I tested the stateful option to save the states of my grid in local_storage, but when i activate this options, my server is flood with ajax request from the table.

I also noticed that the filters field increases with each request, and this infinitely. I see also that the operator is 'undefined'

Here is a sample of received params:

`Started GET "/amis/animal_care_facilities/2/animal_types/12.json?table_id=animal_type_12&sort=sex&dir=desc&filter=%5B%7B%22operator%22%3A%22undefined%22%2C%22value%22%3A%22%7B%22%2C%22property%22%3A%220%22%7D%2C%7B%22operator%22%3A%22undefined%22%2C%22value%22%3A%22%22%22%2C%22property%22%3A%221%22%7D%2C%7B%22operator%22%3A%22undefined%22%2C%22value%22%3A%220%22%2C%22property%22%3A%222%22%7D%2C%7B%22operator%22%3A%22undefined%22%2C%22value%22%3A%22%22%22%2C%22property%22%3A%223%22%7D%2C%7B%22operator%22%3A%22undefined%22%2C%22value%22%3A%22%3A%22%2C%22property%22%3A%224%22%7D%2C%7B%22operator%22%3A%22undefined%22%2C%22value%22%3A%22%7B%22%2C%22property%22%3A%225%22%7D%2C%7B%22operator%22%3A%22undefined%22%2C%22value%22%3A%22%22%22%2C%22property%22%3A%226%22%7D%5D&page=0&limit=20&start=0"`

`Started GET "/amis/animal_care_facilities/2/animal_types/12.json?table_id=animal_type_12&sort=sex&dir=desc&filter=%5B%7B%22operator%22%3A%22undefined%22%2C%22value%22%3A%22%7B%22%2C%22property%22%3A%220%22%7D%2C%7B%22operator%22%3A%22undefined%22%2C%22value%22%3A%22%22%22%2C%22property%22%3A%221%22%7D%2C%7B%22operator%22%3A%22undefined%22%2C%22value%22%3A%220%22%2C%22property%22%3A%222%22%7D%2C%7B%22operator%22%3A%22undefined%22%2C%22value%22%3A%22%22%22%2C%22property%22%3A%223%22%7D%2C%7B%22operator%22%3A%22undefined%22%2C%22value%22%3A%22%3A%22%2C%22property%22%3A%224%22%7D%2C%7B%22operator%22%3A%22undefined%22%2C%22value%22%3A%22%7B%22%2C%22property%22%3A%225%22%7D%2C%7B%22operator%22%3A%22undefined%22%2C%22value%22%3A%22%22%22%2C%22property%22%3A%226%22%7D%2C%7B%22operator%22%3A%22undefined%22%2C%22value%22%3A%220%22%2C%22property%22%3A%227%22%7D%2C%7B%22operator%22%3A%22undefined%22%2C%22value%22%3A%22%22%22%2C%22property%22%3A%228%22%7D%2C%7B%22operator%22%3A%22undefined%22%2C%22value%22%3A%22%3A%22%2C%22property%22%3A%229%22%7D%2C%7B%22operator%22%3A%22undefined%22%2C%22value%22%3A%22%22%22%2C%22property%22%3A%2210%22%7D%5D&page=0&limit=20&start=0"`

**Comment by MikhailTatsky** [comment]
Hi @gspfranc,
Thank you for you question.
Please do the following.
1 - Update lib to latest build.
2 - Remove all from `localStorage` over `localStorage.clear()` in web console.
3 - Try again the same.

We had double encoding in case of server filtering. Now it should work proper.

**Comment by gspfranc** [comment]
Tried today with Build: 1.7.65 and not working as expected.

**Comment by gspfranc** [comment]
Here is my local_storage content:
`{"sorters":"[{\"key\":\"sex\",\"dir\":\"DESC\",\"type\":\"string\",\"_type\":\"string\"}]","columns":"[{\"type\":\"select\",\"draggable\":false,\"locked\":true,\"menu\":false,\"headerCheckBox\":false,\"index\":\"$selected\",\"width\":35,\"editable\":true},{\"index\":\"identification_8\",\"title\":\"Identifiant local\",\"type\":\"string\",\"resizable\":true,\"sortable\":true,\"draggable\":true,\"menu\":true,\"flex\":1,\"filter\":\"OBJECT\",\"width\":135,\"ellipsis\":true},{\"index\":\"id\",\"title\":\"Identifiant Nagano\",\"type\":\"string\",\"render\":\"FUNCTION\",\"resizable\":true,\"sortable\":true,\"draggable\":true,\"menu\":true,\"flex\":1,\"filter\":\"OBJECT\",\"width\":135,\"ellipsis\":true},{\"index\":\"status\",\"title\":\"Status\",\"type\":\"string\",\"filter\":\"OBJECT\",\"render\":\"FUNCTION\",\"resizable\":true,\"sortable\":true,\"draggable\":true,\"menu\":true,\"flex\":1,\"width\":135,\"ellipsis\":true},{\"index\":\"sex\",\"title\":\"Sexe\",\"type\":\"string\",\"render\":\"FUNCTION\",\"resizable\":true,\"sortable\":true,\"draggable\":true,\"menu\":true,\"flex\":1,\"filter\":\"OBJECT\",\"width\":135,\"ellipsis\":true},{\"index\":\"age_day\",\"title\":\"Age (jours)\",\"type\":\"number\",\"resizable\":true,\"sortable\":true,\"draggable\":true,\"menu\":true,\"flex\":1,\"filter\":\"OBJECT\",\"width\":135,\"ellipsis\":true},{\"index\":\"age_week\",\"title\":\"Age (semaine)\",\"type\":\"number\",\"render\":\"FUNCTION\",\"resizable\":true,\"sortable\":true,\"draggable\":true,\"menu\":true,\"flex\":1,\"filter\":\"OBJECT\",\"width\":135,\"ellipsis\":true},{\"index\":\"strain\",\"title\":\"Lignée\",\"type\":\"string\",\"flex\":1,\"resizable\":true,\"sortable\":true,\"draggable\":true,\"menu\":true,\"filter\":\"OBJECT\",\"width\":135,\"ellipsis\":true},{\"index\":\"f_value\",\"title\":\"f\",\"type\":\"number\",\"flex\":1,\"resizable\":true,\"sortable\":true,\"draggable\":true,\"menu\":true,\"filter\":\"OBJECT\",\"width\":135,\"ellipsis\":true},{\"index\":\"n_value\",\"title\":\"n\",\"type\":\"number\",\"flex\":1,\"resizable\":true,\"sortable\":true,\"draggable\":true,\"menu\":true,\"filter\":\"OBJECT\",\"width\":135,\"ellipsis\":true},{\"index\":\"project_number\",\"title\":\"Projet\",\"type\":\"string\",\"flex\":1,\"resizable\":true,\"sortable\":true,\"draggable\":true,\"menu\":true,\"filter\":\"OBJECT\",\"width\":135,\"ellipsis\":true},{\"index\":\"location_name\",\"title\":\"Emplacement\",\"type\":\"string\",\"flex\":1,\"resizable\":true,\"sortable\":true,\"draggable\":true,\"menu\":true,\"filter\":\"OBJECT\",\"width\":135,\"ellipsis\":true},{\"index\":\"lists\",\"title\":\"Listes\",\"type\":\"string\",\"sortable\":false,\"filter\":\"OBJECT\",\"render\":\"FUNCTION\",\"resizable\":true,\"draggable\":true,\"menu\":true,\"flex\":1,\"width\":135,\"ellipsis\":true},{\"index\":\"notes\",\"title\":\"Notes\",\"type\":\"string\",\"filter\":\"OBJECT\",\"render\":\"FUNCTION\",\"resizable\":true,\"sortable\":true,\"draggable\":true,\"menu\":true,\"flex\":1,\"width\":135,\"ellipsis\":true}]","page":0,"filters":"{\"0\":{\"0\":\"{\"},\"1\":{\"0\":\"\\\"\"},\"2\":{\"0\":\"f\"},\"3\":{\"0\":\"_\"},\"4\":{\"0\":\"v\"},\"5\":{\"0\":\"a\"},\"6\":{\"0\":\"l\"},\"7\":{\"0\":\"u\"},\"8\":{\"0\":\"e\"},\"9\":{\"0\":\"\\\"\"},\"10\":{\"0\":\":\"},\"11\":{\"0\":\"{\"},\"12\":{\"0\":\"\\\"\"},\"13\":{\"0\":\"\\\"\"},\"14\":{\"0\":\":\"},\"15\":{\"0\":\"3\"},\"16\":{\"0\":\"}\"},\"17\":{\"0\":\"}\"},\"f_value\":{\"\":3}}"}`

**Comment by MikhailTatsky** [comment]
Let's connect over Slack, please.
Our engineer could study your app over TeamViewer.
If it is suitable then provide us your email here or on support email: support@fancygrid.com

**Comment by MikhailTatsky** [comment]
It was fixed in previous release.
