### ISSUE TITLE
Drag Row Event

### ISSUE THREAD

**Issue by bradsapp** [FancyGrid/FancyGrid#108]
I want to sort the table by an ID. I also want to allow users to drag the rows and save the new order. Also, is there a way to re-arrange columns save those these?

**Comment by MikhailTatsky** [comment]
Good day Brad,
Thank for your questions.

About drag row event.
There is not-documented event: `dragrows`.
You can try it now. We will add information about it soon.
I think over it you can reach "I also want to allow users to drag the rows and save the new order".

"Also, is there a way to re-arrange columns save those these?"
 Do you need API method?
At the moment it is absent, we will try to add it soon.
Maybe this methods will be useful.
https://fancygrid.com/api/methods/hidecolumn
https://fancygrid.com/api/methods/showcolumn

**Comment by MikhailTatsky** [comment]
This event was added in doc
https://fancygrid.com/api/config/events/dragrows
Sample:
https://jsfiddle.net/fancygrid/0t953kqh/

About sorting by id.
There 2 ways:
1 - To add `id` column.
2 - To use method `sort`
https://fancygrid.com/api/methods/sort
