### ISSUE TITLE
Disable expand button when no data avalable

### ISSUE THREAD

**Issue by bojkokudret** [FancyGrid/FancyGrid#109]
When using expander . How do you disable the expand function and icon when there is no data in the expand column?

**Comment by MikhailTatsky** [comment]
Good day Kudret.
Thank you for your question.
At the moment it is not possible.
We will try to add in one of next release.

**Comment by MikhailTatsky** [comment]
Sorry for delayed answer.
We enabled it.
It is possible to reach this over such approach.

```
columns: [{
  type: 'expand',
  render: function(o){
    if(o.data.sold.length === 0){
      o.hidden = true;
    }
    return o;
  },
},{
```
In next days, I will try to provide sample.

**Comment by MikhailTatsky** [comment]
Sample:
https://jsfiddle.net/fancygrid/dxy9m2w5/
