### ISSUE TITLE
How to get data filtered?

### ISSUE THREAD

**Issue by dreaming1402** [FancyGrid/FancyGrid#11]
Dear Support Team,
How can I get all data filtered on fancygrid?
I have to see the method: .getData() and .getDataView() but not have the .getDataFilter(). I't is available on fancygrid?
Please help me get all filtered data on fancygrid, thank you!

**Comment by MikhailTatsky** [comment]
Currently this method is absent.
But you can get filtered data over this
```grid.store.filteredData```

**Comment by dreaming1402** [comment]
Yes, but this option may be include in future?

**Comment by MikhailTatsky** [comment]
In next release it will be avaliable over  
```grid.getDataFiltered()```

**Comment by MikhailTatsky** [comment]
It was done.
Please read comment in issue #9
