### ISSUE TITLE
FancyGrid Server Filtering Tutorial bug/syntax error?

### ISSUE THREAD

**Issue by Juliusssssssss** [FancyGrid/FancyGrid#110]
Hi,
I was playing around with different grids and they all work fine, but the Server Filtering grid tutorial.
I get an error/ syntax error in the load.php
```
for($i=0;$ioperator);
		$value = $filterItem->value;
		$property = $filterItem->property;
		
		if($operator === 'LIKE'){
			$filter .= "`" . $property . "` " . $operator . " '%" . $value . "%'";
		}
		else{
			$filter .= "`" . $property . "` " . $operator . " '" . $value . "'";
		}
		
		if($i !== count($_filter) - 1 ){
			$filter .= 'AND';
		}
	}
  }
```
My database won't load using the Server Filtering grid. I had no issues with other server grids tho. Should I be looking further for some mistake on my side or is there some bug/error?

Thanks guys

**Comment by MikhailTatsky** [comment]
@Juliusssssssss 
 Thank you for evaluating our product.
Server filtering is one of the most complex feature.
Please, provide your email that we could add your email in Slack.
It requires to connect with us and try TeamViewer to get your case better.
