### ISSUE TITLE
How to load the data and column names dynamically?

### ISSUE THREAD

**Issue by pedy711** [FancyGrid/FancyGrid#111]
I tried the following code but it didn't show the grid. Our use case requires that we feed the grid with columns names and data which come from the server. Could you please provide us with a sample that works with the remote data?

    this.service.fetch(this.tableReportstate).subscribe((item) => {

    let newColumns: any[] = new Array();
        item.gridState.columns.forEach(element => {
          newColumns.push({
            "index": element.title,
            "title": element.title
          })
        });

        this.gridConfig = {
          width: 450,
          height: 400,
          selModel: 'rows',
          trackOver: true,
          theme: 'gray',
          data: item.data,
          defaults: {
            type: 'string',
            sortable: true,
            resizable: true,
            width: 100
          },
          columns: newColumns
        };
     }

**Comment by MikhailTatsky** [comment]
Good day @pedy711,
By code it looks like you missed `field` for columns.

We advice you to study our Tutorials.
https://fancygrid.com/tutorials/

**Comment by MikhailTatsky** [comment]
Also needs to know more about data structure.

**Comment by pedy711** [comment]
Good day, thanks for your prompt reply, I very much appreciate it. 
I don't think `field ` would be the missing factor here, because I even replaced the following code (your sample code on the website) in there:

    this.service.fetch(this.tableReportstate).subscribe((item) => {
        const data = [
          { name: 'Ted', surname: 'Smith', company: 'Electrical Systems', age: 30 },
          { name: 'Ed', surname: 'Johnson', company: 'Energy and Oil', age: 35 },
          { name: 'Sam', surname: 'Williams', company: 'Airbus', age: 38 },
          { name: 'Alexander', surname: 'Brown', company: 'Renault', age: 24 },
          { name: 'Nicholas', surname: 'Miller', company: 'Adobe', age: 33 },
          { name: 'Andrew', surname: 'Thompson', company: 'Google', age: 28 },
          { name: 'Ryan', surname: 'Walker', company: 'Siemens', age: 39 },
          { name: 'John', surname: 'Scott', company: 'Cargo', age: 45 },
          { name: 'James', surname: 'Phillips', company: 'Pro bugs', age: 30 },
          { name: 'Brian', surname: 'Edwards', company: 'IT Consultant', age: 23 },
          { name: 'Jack', surname: 'Richardson', company: 'Europe IT', age: 24 },
          { name: 'Alex', surname: 'Howard', company: 'Cisco', age: 27 },
          { name: 'Carlos', surname: 'Wood', company: 'HP', age: 36 },
          { name: 'Adrian', surname: 'Russell', company: 'Micro Systems', age: 31 },
          { name: 'Jeremy', surname: 'Hamilton', company: 'Big Machines', age: 30 },
          { name: 'Ivan', surname: 'Woods', company: '', age: 24 },
          { name: 'Peter', surname: 'West', company: 'Adobe', age: 26 },
          { name: 'Scott', surname: 'Simpson', company: 'IBM', age: 29 },
          { name: 'Lorenzo', surname: 'Tucker', company: 'Intel', age: 29 },
          { name: 'Randy', surname: 'Grant', company: 'Bridges', age: 30 },
          { name: 'Arthur', surname: 'Gardner', company: 'Google', age: 31 },
          { name: 'Orlando', surname: 'Ruiz', company: 'Apple', age: 32 }
        ];

        this.gridConfig = {
          width: 450,
          height: 400,
          selModel: 'rows',
          trackOver: true,
          theme: 'gray',
          data: data,
          defaults: {
            type: 'string',
            sortable: true,
            resizable: true,
            width: 100
          },
          columns: [{
            type: 'select'
          }, {
            index: 'company',
            title: 'Company'
          }, {
            index: 'name',
            title: 'Name'
          }, {
            index: 'surname',
            title: 'Sur Name'
          }, {
            index: 'age',
            title: 'Age',
            width: 50,
            type: 'number'
          }]
        };
     }

 But I still get the following error:

> ERROR TypeError: Cannot read property 'renderTo' of undefined
>     at FancyGridComponent.push../node_modules/fancy-grid-angular/fesm5/fancy-grid-angular.js.FancyGridComponent.ngAfterViewInit 

It works when I inject your code, as explained, in the constructor because `gridConfig ` becomes available to the html tag `<fancy-grid-angular>` immediately, but when it is sort of lazy loaded then it throws that error.

Anyways, I will check out your tutorials now :)

**Comment by MikhailTatsky** [comment]
It looks like I got the problem.
Please define id like here
```
<fancygrid id="myGrid" fg-config="config"></fancygrid>
```
It looks like grid tries to render to some element but it does not exist.

Let me ask, do you use AngularJS? Which version?

**Comment by pedy711** [comment]
I'm using the following tag
`<fancy-grid-angular *ngIf="showFancyGrid" [config]="gridConfig"></fancy-grid-angular>
`

but I also tried to add `id="myGrid"` and set `renderTo: 'myGrid'`, but no luck.

I am using Angular 7

**Comment by pedy711** [comment]
It would be really great if you could create a sample project using https://stackblitz.com/ as a showcase

**Comment by MikhailTatsky** [comment]
Thank you for provided information.
We will study it. I will write you back today or tommorow.

**Comment by MikhailTatsky** [comment]
@pedy711 
 Here is basic init of grid for Angular.
https://stackblitz.com/edit/angular-fms2ox

It looks like I do not understand right your situation.
Could you try to replicate problem on that sample, please?

Maybe you have grid instance already and want to reconfig grid or something.

**Comment by pedy711** [comment]
thanks, but this is the grid using the local data. Could you please provide an example using remote data? Like this one from Telerik Kendo UI for Angular: 

https://stackblitz.com/edit/angular-ykbsk5

I actually would like to see how do you configure the columns once you get the data from the server.

**Comment by MikhailTatsky** [comment]
@pedy711 
In provided exactly columns are set on start
```
 <kendo-grid
          [data]="query | async"
          [loading]="loading"
          [skip]="state.skip"
          [pageSize]="state.take"
          scrollable="virtual"
          [rowHeight]="36"
          [height]="450"
          (pageChange)="pageChange($event)"
        >
        <kendo-grid-column field="OrderID" [width]="80" title="ID"></kendo-grid-column>
        <kendo-grid-column field="ShipName" title="Ship Name" [width]="200"></kendo-grid-column>
        <kendo-grid-column field="ShipAddress" title="Ship Address" [width]="200"></kendo-grid-column>
        <kendo-grid-column field="ShipCity" title="Ship City" [width]="100"></kendo-grid-column>
        <kendo-grid-column field="ShipCountry" title="Ship Country" [width]="100"></kendo-grid-column>
      </kendo-grid>
```

And only data is get from server.
If you need to set data dynamicly in grid then you need 
to use method
https://fancygrid.com/api/methods/setdata
About using methods you can read here
https://fancygrid.com/api/methods

But it is very simple case, usually for working with server it requires to config `data.proxy`.
Then grid will do all this work by self.
https://fancygrid.com/api/config/data/proxy
As I wrote before, about working with server you can read in Tutorials section.
https://fancygrid.com/tutorials/

**Comment by MikeTatsky** [comment]
Updates:
Maybe new method will be helpful.
https://fancygrid.com/api/methods/setcolumns
