### ISSUE TITLE
dragrows function error

### ISSUE THREAD

**Issue by massarakhsh** [FancyGrid/FancyGrid#113]
Drag the row to up works correctly
Drag to down one line lower than indicated by the mouse

**Comment by MikhailTatsky** [comment]
Thank you very much for the report.
We will check it.

**Comment by MikhailTatsky** [comment]
Thank you for the report.
We will try to fix it in next release.

**Comment by MikhailTatsky** [comment]
This bug was fixed with latest release.

**Comment by massarakhsh** [comment]
> This bug was fixed with latest release.

Downloaded the release yesterday - the error is not fixed

**Comment by MikhailTatsky** [comment]
On my side, it works.
https://drive.google.com/file/d/12IcKY8vTgNoZ2fWObreNafTsoAbw0Qn3/view

Could you do screencast and provide some extra information about behavior, please.
http://screencastify.com is good for screencast.

**Comment by massarakhsh** [comment]
You're right.
Release by 4 Jun 20:35 works,
release by 2 Jun 18:54 didn't work.
Thank you.
