### ISSUE TITLE
How call addFilter for grid column type combo?

### ISSUE THREAD

**Issue by massarakhsh** [FancyGrid/FancyGrid#115]
I tried this:
grid.addFilter(index, ['Alpha','Beta'], '=')
grid.addFilter(index, {'Alpha':true,'Beta':true}, '|')
It doesn't work.
How should I?

**Comment by MikhailTatsky** [comment]
Very good question,
Please, study this doc link.
http://fancygrid.com/api/methods/addfilter
Sample at the bottom.
```
grid.waitingForFilters = true;
grid.addFilter('name', 'Nick');
grid.addFilter('surname', 'Thomson');
grid.updateFilters();// It will update grid and set waitingForFilters to false.
```

**Comment by massarakhsh** [comment]
Unfortunately, there are no examples for working with column.type="combo" in this guide (((

**Comment by MikhailTatsky** [comment]
Try this.
`grid.addFilter('name', ['Nick', 'Peter'], '=');`

With your case.
This variant should work `grid.addFilter(index, ['Alpha','Beta'], '=')`.

Do you have in column index?
Could you provide code of columns and 1row data, please?

**Comment by massarakhsh** [comment]
// Extraction from my code

function fancy_build_bind(parm) {
    let instant = {
        //license: XXXX,
        renderTo: parm.id,
        columns: [
            {
                title: "role", index: "role", type: "string", filter: { header: true }
            },
            {
                title: "firm", index: "firm", type: "combo", filter: { header: true },
                displayKey: "name", valueKey: "name",
                multiSelect: true, itemCheckBox: true, data: [
                { name: "bear" },
                { name: "cat" },
                { name: "egle" }
            ]}
        ],
        default: {
            type: "string",
            width: 100
        },
        events: [
            { init: fancy_init }
        ],
        data: { items: [
                { role: "member", firm: "cat" },
                { role: "member", firm: "egle" },
                { role: "admin", firm: "bear" },
                { role: "member", firm: "cat" }
            ]}
    };
    FancyWindowGrid = new FancyGrid(instant);
}

function fancy_init(grid) {
    grid.waitingForFilters = true;
    grid.addFilter('role','member');                // It's OK, filter working
    //grid.addFilter('firm',"cat", '=');   // It's error. fatal crash
    //grid.addFilter('firm',["cat"], '=');   // It's error. fatal crash
    //grid.addFilter('firm',{"cat":true}, '|');   // It's error. fatal crash
    grid.updateFilters();
}

**Comment by MikhailTatsky** [comment]
You found bug :(
Comment these lines and it will work.
```
multiSelect: true,
itemCheckBox: true,
```

We will try to fix it ASAP.
If it will be successful than we will add on tomorrow release.

P.S.:
Thank you very much for the report.

**Comment by massarakhsh** [comment]
It is work.
But I need both multi selections and checkboxes ((
Thank you, I will wait.

**Comment by MikhailTatsky** [comment]
Release was done.
It was enabled the simplest version for combo.
`grid.addFilter('firm',['cat', 'bear']);`

We will try to enable all other filter signs in next releases.

**Comment by massarakhsh** [comment]
Thank you, this is what I need!

**Comment by MikhailTatsky** [comment]
Glad to help :)
Thank you for the bug report!
