### ISSUE TITLE
How to style the text from "fancy-grid-header-cell-group-level-2" ?

### ISSUE THREAD

**Issue by KrystynaPrykhodko** [FancyGrid/FancyGrid#117]
I would like to attend a class to text from header-text Level 2 like for column the class "myClass":
```
{
  text: 'Magnetom Aera',
  columns: [{
    title: 'IPB',
    index: 'IPB_Magnetom_Aera',
    cls: 'myClass',
  },
```

Thank you in Advance
Krystyna

**Comment by MikhailTatsky** [comment]
Good day Krystyna,
Thank you for your question.

Sorely at the moment, there is no way to add class name to group header cells.
It is possible to style over css all group header cells but some exact one, not possible.

We will try to add this feature in one of next releases.

**Comment by krystynaMond** [comment]
Tank you for the response.
How to style over css all group header cells?

**Comment by MikhailTatsky** [comment]
```
.fancy-grid-header-cell-group-level-2 {
  background-color: gray;
  color: white;
}
```

**Comment by KrystynaPrykhodko** [comment]
Thanks for your answer
That helped me
