### ISSUE TITLE
NPM Package License error

### ISSUE THREAD

**Issue by Jogai** [FancyGrid/FancyGrid#118]
The npm registry states that its MIT licensed. To my surprise I got this warning in the console:

```
FancyGrid Trial Version!
Purchase license for legal usage!
Sales email: sales@fancygrid.com
```

**Comment by MikhailTatsky** [comment]
Thank you for your question.
Our product is 100% commercial.
The matter is npm adds to all packages information that they are under MIT license if you did not
purchased subscription.

**Comment by MikhailTatsky** [comment]
We fixed license issue for main package https://www.npmjs.com/package/fancygrid
