### ISSUE TITLE
How to find a grid object?

### ISSUE THREAD

**Issue by massarakhsh** [FancyGrid/FancyGrid#119]
Hello,
Is there a universal way to find a FancyGrid object from handler event? Attributes and fields change in different versions, I would like something like "let grid = item.getGrid()"
And a similar question about the form, please.

**Comment by MikhailTatsky** [comment]
Good day,
1 - All grid events has first argument that is grid.
2 - Read doc section about methods.
https://fancygrid.com/docs/grid-concepts/methods
You can get link on grid over
a) `id`
`var grid = Fancy.getWidget('myGrid');`
b) over `renderTo` element
var grid = FancyGrid.get('myGridReport');

**Comment by massarakhsh** [comment]
Thank you

**Comment by evbrew** [comment]
If grid was created using JQUERY, what is the syntax to get a reference to that grid later?

For example, i create grid with
$('#imageFieldContainer').FancyGrid({ //omitted params

But i cant seem to get a reference to the grid to invoke methods using JQUERY like
$('#imageFieldContainer').FancyGrid().update();

**Comment by MikeTatsky** [comment]
@evbrew 
You still need to define `id` in options of grid.
