### ISSUE TITLE
Is possible dynamicaly fill column without reload which depends of other column?

### ISSUE THREAD

**Issue by MirlanBekturov** [FancyGrid/FancyGrid#12]
Hello! I want to autofill column after fill other columns without reload, for example get additional info from url column (call ajax and fill getting data). Is it possible and how can I do it? Thank you!

**Comment by MikhailTatsky** [comment]
You can manipulate with grid in any way you like.
There are methods
https://fancygrid.com/api/methods/set
https://fancygrid.com/api/methods/setbyid

Also this one could be useful
https://fancygrid.com/api/methods/update

**Comment by MikeTatsky** [comment]
Some updates for this issue.
We added new grid method for changing columns.
https://fancygrid.com/api/methods/setcolumns
