### ISSUE TITLE
How to get the Attributes and classnames from header?

### ISSUE THREAD

**Issue by KrystynaPrykhodko** [FancyGrid/FancyGrid#120]
Hello MikhailTatsky,

I know there is a function get().
How can I get an attribute, classname, stylevalue using method get()? Or is there another method for it?
Here is an example:

I have 
`<div` class="fancy-grid-header-cell fancy-grid-header-cell-group-level-2" `index="1">`
How ca I get the classname, indexvalue, backgroundcolor or another information for Example?

Thank you in advance
Krystyna

**Comment by MikhailTatsky** [comment]
Are you looking for this?
https://fancygrid.com/api/methods/getheadercell

```
var cell = grid.getHeaderCell('name');
```

In `cell.dom` HTML dom element that has all JavaScript methods for getting attributes and all other actions.

**Comment by KrystynaPrykhodko** [comment]
Fank you for your request. 
I use this
var cell = grid.getHeaderCell('name');
console.log(cell);
 
But I get this: 
fancy.full.min.js:9 Uncaught TypeError: Cannot read property 'getCell' of undefined

That is the 'name' in this case?

**Comment by MikhailTatsky** [comment]
@KrystynaPrykhodko 
 In this case `name` is column data index.
If you do not have column with this data index, it generates bug.

**Comment by KrystynaPrykhodko** [comment]
excellent!

Is that possible to add a class to fancy-grid-header-cell-group-level-2  ?
Is it possible to add such an ID or other attributes?

**Comment by MikhailTatsky** [comment]
@KrystynaPrykhodko 
About getting second `fancy-grid-header-cell-group-level-2`, at the moment there is not API.
We will try to add it in future.

**Comment by MikeTatsky** [comment]
@KrystynaPrykhodko 
I am sorry for long preparing feature.
We are also did release with styling group header cells.
Here is sample.
https://jsfiddle.net/fancygrid/sL18fe9b/

**Comment by KrystynaPrykhodko** [comment]
Hello Mike,

this is an elegant solution,
thanks a lot !
