### ISSUE TITLE
Choose between these fields in the grid table with the arrow keys

### ISSUE THREAD

**Issue by KrystynaPrykhodko** [FancyGrid/FancyGrid#122]
Now I would like to be able to choose between these fields in the grid table with the arrow keys in all directions, so that I can quickly enter or change values similar to an Excel table. How can you do this in FancyGrid?
Fank you for your help in Advance.

Best regard
Krystyna

**Comment by MikhailTatsky** [comment]
Good day Krystyna,
I think you are looking for these links.
https://fancygrid.com/api/config/selmodel/selectbottomcellafteredit
https://fancygrid.com/api/config/selmodel/selectbottomcellondown
https://fancygrid.com/api/config/selmodel/selectleftcellonleftend
https://fancygrid.com/api/config/selmodel/selectrightcellonend
https://fancygrid.com/api/config/selmodel/selectupcellonup
