### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'a.length')

### ISSUE THREAD

**Issue by viandham** [FancyGrid/FancyGrid#123]
Hi

I can't get data from URL to work. I used a static dataset in json while configuring my columns etc and that works fine, but when I tried to switch over to fetching the JSON from url it failed.
I used the example here for simplicity, get the same error there:
https://fancygrid.com/tutorials/server/json-file
but obviously changed the url to something meaningful. The response is in the format:
```javascript
[{
    "Username": "xxx",
    "Registered": null,
    "ICCID": null,
    "GroupName": "Default",
    "AccountingFirstSeen": "2016-03-23T00:00:00",
    "AccountingLastSeen": "2016-12-20T00:00:00",
    "TotalReceivedBytes": 1,
    "TotalSentBytes": 2
}, {
    "Username": "yyy",
    "Registered": null,
    "ICCID": null,
    "GroupName": "Default",
    "AccountingFirstSeen": "2016-04-06T00:00:00",
    "AccountingLastSeen": "2019-11-12T00:00:00",
    "TotalReceivedBytes": 3,
    "TotalSentBytes": 4
}]
```
The URL works fine, it takes about 1 second to fetch 500+ rows and it displays data in the network inspection in the browser.

The error I get in the console is this:
```TypeError: undefined is not an object (evaluating 'a.length')```

Tried in both Safari and Chrome.
The grid itself shows the loading animation but does not refresh the grid after the url is fetched.

Am I doing something wrong or is this a bug?

**Comment by MikhailTatsky** [comment]
Good day Andreas,
Thank you for your question.
You need to wrap data items like this
```
{
  "data": [
    {"id": 1, "name": "Taylor", "surname": "Davis", "country": "Netherlands", "position": "DevOps", "email": "taylor.davis@fancygrid.com"},
   ...
  ]
}
```

Example:
https://fancygrid.com/ajax/users.json

**Comment by viandham** [comment]
That obviously works a lot better.
I incorrectly assumed that I could take the response and throw it into a variable and it would be the same.

Thanks for the fast response and an awesome grid tool!

**Comment by MikhailTatsky** [comment]
You can disable wrapping over this.
https://fancygrid.com/api/config/data/proxy/wrapper
But it will limit functionality a bit in case of server paging.

Note:
Hard clear if you will use disabling wrapper.

**Comment by viandham** [comment]
Great, thank you for your help!
