### ISSUE TITLE
About the Custom Template with Each Cell.

### ISSUE THREAD

**Issue by iewihc** [FancyGrid/FancyGrid#124]
Hello . 

I want to make a cell could be click. and popup a select-window 

like this gif.
https://upload.cc/i1/2020/03/16/KVDlF5.gif

I have no idea how to do that. Can you help me ?

**Comment by MikhailTatsky** [comment]
Good day @iewihc,
Thank you for your question.

Not sure that I got case right.
1 - In gif it shows row editor.
We have row editor
https://fancygrid.com/samples/edit/row
If you double click on cell, it will show row editor.
At the moment, it is not possible to add custom elements in row editor.

2 - We have controller.
You can render custom elements and set global event delegator.
https://fancygrid.com/samples/events/controllers

3 - About showing window.
In this sample, if you will double click on cell it will show popup editor.
https://fancygrid.com/dashboards/staff/
