### ISSUE TITLE
API: Sorting of grid

### ISSUE THREAD

**Issue by massarakhsh** [FancyGrid/FancyGrid#125]
I can get filters as grid.filter.filter
How do I determine the current sorting by grid?

**Comment by MikhailTatsky** [comment]
Thank you for very good question.

About filter.
We added method `getFilter` that to get it in flexible way.
https://fancygrid.com/api/methods/getfilter

About sort info.
You can get it over
`grid.store.sorters`
We will try to add method that to do it over API in one of next releases.

**Comment by MikhailTatsky** [comment]
@massarakhsh 
We just did release with method `getSorter`
Doc link:
https://fancygrid.com/api/methods/getsorter
