### ISSUE TITLE
fancygrid expand

### ISSUE THREAD

**Issue by mehmettokmak** [FancyGrid/FancyGrid#126]
Hello good day,
I use the fancygrid expand feature, but only one open at a time, the others close. can you help me please?
**grid.collapseall ();** I tried command but I was not successful

![image](https://user-images.githubusercontent.com/36069734/78540561-0145bc00-77fd-11ea-8bf7-bec6cfa6779b.png)

**Comment by mehmettokmak** [comment]
![image](https://user-images.githubusercontent.com/36069734/78540503-ef641900-77fc-11ea-8eec-7d71ff926564.png)

**Comment by MikhailTatsky** [comment]
Good day @mehmettokmak 
Thank you for the report.
Could you provide extra information, please?

1 - Which framework do you use? Angular, React, Vue,  jQuery, Vanilla JS?
2 - Version of FancyGrid.
You can know it if in web console to type `Fancy.version`.
3 - Do you have any errors in web console?
4 - Do you use server paging, sorting, filter of FancyGrid?

**Comment by mehmettokmak** [comment]
1- jQuery
2- Build v1.7.87
3-no errors appear on console
4- i don't use any

![image](https://user-images.githubusercontent.com/36069734/78542074-4ec32880-77ff-11ea-8195-520b16da42d6.png)

**Comment by MikhailTatsky** [comment]
Thank you for details.
We will study this issue and write you back.

**Comment by mehmettokmak** [comment]
thank you I am waiting for your reply

**Comment by MikhailTatsky** [comment]
@mehmettokmak 
 It is miss of our product.
Methods support only tree data not this feature.
https://fancygrid.com/api/methods/collapse
https://fancygrid.com/api/methods/collapseall

We will try to extend our API to enable these methods for row expander.
We plan to do release on this weekend.

**Comment by mehmettokmak** [comment]
How can I be notified when this feature is enabled?

**Comment by MikhailTatsky** [comment]
@mehmettokmak 
I will write you back about it here.

**Comment by mehmettokmak** [comment]
OK thank you

**Comment by MikhailTatsky** [comment]
@mehmettokmak 
As ASAP solution:

```
grid.expander.reSet();
grid.expander.clearExpandedCheckBoxes();
```

**Comment by mehmettokmak** [comment]
thank you this code worked for my program. but i have one more problem. When I open a closed line, it has to close the open ones, but I couldn't.


![image](https://user-images.githubusercontent.com/36069734/78862740-bddb8f80-7a40-11ea-809f-388dc0f4639d.png)

**Comment by MikhailTatsky** [comment]
@mehmettokmak 
Sends us your email on support@fancygrid.com we will add you in Slack for support.
We coud try TeamViewer to detect problem if it is ok by your company security policy.

**Comment by MikeTatsky** [comment]
I will close this issue. It was resolved.
If you have any extra questions about it, you can reopen this issue.
