### ISSUE TITLE
proxy.autoLoad does not work

### ISSUE THREAD

**Issue by massarakhsh** [FancyGrid/FancyGrid#127]
My code:
grid.data.remoteLoad = true;
grid.data.proxy.url = url;
grid.data.proxy.autoLoad = false;
Unfortunately, data loading automatically.
Can I load data only by grid.load() ?

**Comment by MikhailTatsky** [comment]
1 - This option `grid.data.remoteLoad` does not exist.
2 - 
`grid.data.proxy.url = url;`
`grid.data.proxy.autoLoad = false;`
It should be set in configs on start.
```
data: {
  proxy: {
    autoLoad: false,
    url: 'clients.php'
  }
},
```

**Comment by massarakhsh** [comment]
I'm sorry, here is the real code

it.Grid.SetParameter(true,"data/remoteSort")
it.Grid.SetParameter(true,"data/remoteFilter")
it.Grid.SetParameter(url,"data/proxy/url")
it.Grid.SetParameter(false,"data/proxy/autoLoad")
it.Grid.SetParameter("rest","data/proxy/type")
it.Grid.SetParameter("POST","data/proxy/methods/read")
,it.Grid.SetParameter("items","data/proxy/reader/root")

Option autoLoad does not work.
Changing the sorting method, for example, results in an immediate request to the server.

**Comment by MikhailTatsky** [comment]
Are you using ASP?
By first view you set data options after init of grid but it requires to do it before.

**Comment by massarakhsh** [comment]
Before init, of course.
JS-code:
    let instant = {...};
    instant.data = {
        remoteSort:true,
        remoteFilter:true,
        proxy:{
            url:"/front/bell/all/seekgrid?_sp=564215620",
            autoLoad:false,
            type:"rest",
            methods:{
                read:"POST"
            },
            reader:{
                root:"items"
            }
        }
    }
    let item = new FancyGrid(instant);

Option autoLoad dos not work.

**Comment by MikhailTatsky** [comment]
Here is live sample with simplest variant of loading json file.
https://fancygrid.com/dashboards/auto-load-false/
I also tested locally with the same API as in your sample but it works proper.
I will try to prepair sample on weekend.
Could you try latest version of FancyGrid, please?

**Comment by massarakhsh** [comment]
Ok, your code works.
And my code works without the "remoteFilter" and "remoteSort" parameters.
With these parameters any change to the filter or sorting causes the data to load without grid.load(). Additional question: can I define filters and sorting BEFORE initializing of the grid? Now I do it after initialization and it causes several unwanted automatic data downloads from the server.

**Comment by MikhailTatsky** [comment]
@massarakhsh 
 You can try state feature
https://fancygrid.com/api/config/state/filters
https://fancygrid.com/api/config/state/sorters

**Comment by massarakhsh** [comment]
Thank you, Mikhail.

**Comment by massarakhsh** [comment]
The state extension is really useful.
Unfortunately, even with data.proxy.autoLoad=false, initialization calls a series of data loads, one for each non-empty filter and sorting element.

**Comment by MikhailTatsky** [comment]
@massarakhsh 
 You can connect with me on Slack.
We will resolve it.
