### ISSUE TITLE
set and refresh data for combo

### ISSUE THREAD

**Issue by KrystynaPrykhodko** [FancyGrid/FancyGrid#129]
Hello,

In the case bellow I try to set and refresh a new data-set using the change-avent. How can I refresh the data in this case?

var list = [{ value: '1'}, {value: '2'}]
var form = new form({
...
items: [{
   type: combo,
   data: list,
   events: [{ 
     change: function(){
       list =  [{ value: '5'}, {value: '6'}];
   }
...
 }]   
}]
})

Fank you very much in advance

**Comment by MikhailTatsky** [comment]
You need to use method setData.
Example:
https://jsfiddle.net/fancygrid/25uqcxdw/

 Study doc section `Methods`.
https://fancygrid.com/apiform/fields/combo

**Comment by MikhailTatsky** [comment]
Question was about form but also update for grid column `combo`.
There is special method for this.
`setColumnComboData`
https://fancygrid.com/api/methods/setcolumncombodata
