### ISSUE TITLE
The fancygrid .load() function have a bug

### ISSUE THREAD

**Issue by dreaming1402** [FancyGrid/FancyGrid#13]
Hello,
I get a bug with fancygrid .load() function.
I't doesn't reload grid view when I filtered something.

Please fix it, thank you

**Comment by MikhailTatsky** [comment]
Can please clearify?
What type of data do you use?
Server side or local(static)

If you use local data that method load should not work. 
Method `load` is specially for server size data.
You can use method `update` instead, but it will not return original data on start.

Or maybe your case is some one else?

**Comment by MikhailTatsky** [comment]
We understood the case.
You have json file and filter locally.
And after filtering you run method load.
If update grid and does not mention filter.

The matter is than you need one of following
1 - use server side filtering
2 - Do not use load method 

If you still need load method than run also clearFilter method.

**Comment by dreaming1402** [comment]
Ok, I will try it again and report late

Many thanks :+1:

**Comment by dreaming1402** [comment]
Again, about another problem with .load() function.

I get this error when I using jquery $(document).ready();
error message: [http://prntscr.com/fxza2b](http://prntscr.com/fxza2b)
this is my code: [http://prntscr.com/fxzcrh](http://prntscr.com/fxzcrh)
