### ISSUE TITLE
auto setting the maxHeigh for context-menu

### ISSUE THREAD

**Issue by xiayuf** [FancyGrid/FancyGrid#131]
when i used more than six items(30*7=210>200)，the context-menu limits the maxheight is 200, and set an "overflow-y": "scroll", how can I  set the maxHeight greater than 200px? Maybe can set the maxHeight more than 400px .Want to a long context-menu like this:
![image](https://user-images.githubusercontent.com/13518087/79899710-bd2efa00-843f-11ea-9edc-61653f5f9820.png)

There are some code about menu.min.js below:
```
itemHeight: 30,
maxHeight: 200,
rendered: !1,
theme: "default",
render: function() {
  var a,
    ...
    b.checkHeight();
},
checkHeight: function() {
  var a = this;
  parseInt(a.el.css("height")) > a.maxHeight &&   // this line limits the height
    a.el.css({
      height: a.maxHeight,
      "overflow-y": "scroll"
    });
},
```[](url)

**Comment by MikhailTatsky** [comment]
@xiayuf 
It is not good configurable.
But you can try do like this.
```
.fancy-menu {
  height: initial !important;
  overflow-y: hidden !important;
}
```
