### ISSUE TITLE
Arbitrary expression as filter

### ISSUE THREAD

**Issue by nicknjpconsultingllc** [FancyGrid/FancyGrid#137]
Hi!

Great job on the library btw, it's awesome.

I'd really like to filter the grid using a relation between two or more columns - something like filter where Column A > Column B.

I haven't found a good way to do this besides computing it server-side and passing true/false down as a new column and filtering on that. Of course, that's not an ideal solution.

An ideal solution would probably be the ability to pass in a function ( (row) => boolean ) and then filter based on that. It doesn't seem possible at the moment. Plus there might be issues serializing this if the user has stateful:true (not a requirement for me).

Any ideas on how to accomplish this?

I'll try modifying the filter code in the meantime and doing a PR if I'm successful. Thanks!

**Comment by nicknjpconsultingllc** [comment]
Nevermind, I think I found it -https://fancygrid.com/api/config/columns/filter/fn

**Comment by nicknjpconsultingllc** [comment]
Found it - https://github.com/FancyGrid/FancyGrid/blob/master/src/js/data/mixins/Filter.js#L221

**Comment by MikeTatsky** [comment]
Maybe these links will be helpful.
https://fancygrid.com/docs/grid-concepts/filtering
https://fancygrid.com/dashboards/filter-form/
https://fancygrid.com/dashboards/stripe-jobs/
https://fancygrid.com/dashboards/flats/
