### ISSUE TITLE
FancyGrid Input event

### ISSUE THREAD

**Issue by KrystynaPrykhodko** [FancyGrid/FancyGrid#138]
Hello Mike,

i would like to use input event for combobox. 
It should react on every character during input.
Is it already implemented in FancyGrid?

Best regard
Krystyna

**Comment by MikeTatsky** [comment]
There are many internal events that you can also use for form combo.
```
'focus', 'blur', 'input',
 'up', 'down', 'change', 'key', 'enter', 'esc',
 'empty',
 'load',
 'add-new-value'
```
But they are not documented yet.

**Comment by KrystynaPrykhodko** [comment]
Fanks for your response.

Which event is similar to the "classic" event INPUT?
I have tried FancyGrid INPUT but see no change

**Comment by MikeTatsky** [comment]
@KrystynaPrykhodko 
Do you try it in form or in grid?
I am afraid that in grid, at the moment you are not able to use it.

**Comment by KrystynaPrykhodko** [comment]
I try it in form

Mike Tatsky <notifications@github.com> schrieb am Di. 22. Sept. 2020 um
19:23:

**Comment by MikeTatsky** [comment]
`key` and `input` events.

By the way. Maybe you are looking for this?
It is formatting on input.
https://fancygrid.com/samples/form/format-input

**Comment by KrystynaPrykhodko** [comment]
Thanks for the tip, it helped !
