### ISSUE TITLE
add images into form

### ISSUE THREAD

**Issue by AlexVesta** [FancyGrid/FancyGrid#14]
Hello, FancyGrid team! 
Is it possible to add images into form? Because now I can't do it. 
https://fancygrid.com/docs/form-concepts/fields
For example, I have a modal form with tabs and one of these should contain images of a product from the main grid. How I can show images inside this form? Or can I insert a grid with images inside a tab of the form?
Thank you.

**Comment by MikhailTatsky** [comment]
Hi Alex.
Do you need this?
https://jsfiddle.net/fancygrid/bvfepfy2/
It was missed it in doc. We will update docs soon.

**Comment by AlexVesta** [comment]
Awesome! thank you!
