### ISSUE TITLE
HTML Tags in Table Cells Break the Filter with MultiSelect Combo

### ISSUE THREAD

**Issue by golanorbi** [FancyGrid/FancyGrid#141]
Hi,

If a table cell contains HTML tags in it, the filter doesn't work in multiselect combo.
The problem seems to be in the fancy.js file where the `<li>'s` of the filter are created.

The `<li>` is rendered like this:

`<li value="<a href="`

The double quotes are closed before time, and are get mixed up with the single quotes, and that breaks the filter from working (when the cell contains HTML tags).

The fix is rather simple:

The single quotes and the double quotes should be replaced with each other.
Meaning, the single quotes should be turned to double quotes, and the double quotes should be turned into single quotes.

So:

1. in **_renderList_**:

instead of:

` if (me.multiSelect && me.itemCheckBox) {
            listHtml.push('<li value="' + value + '" class="' + isActive + '"><div class="' + FIELD_CHECKBOX_INPUT_CLS + '" 
            style=""></div><span class="' + FIELD_COMBO_LIST_VALUE_CLS + '">' + displayValue + '</span></li>');
          } else {
            listHtml.push('<li value="' + value + '" class="' + isActive + '"><span class="' + FIELD_COMBO_LIST_VALUE_CLS + '">' + displayValue + '</span></li>');
          }`

It should be:

`if (me.multiSelect && me.itemCheckBox) {
            listHtml.push("<li value='" + value + "' class='" + isActive + "'><div class='" + FIELD_CHECKBOX_INPUT_CLS + "' 
            style=''></div><span class='" + FIELD_COMBO_LIST_VALUE_CLS + "'>" + displayValue + "</span></li>");
          } else {
            listHtml.push("<li value='" + value + "' class='" + isActive + "'><span class='" + FIELD_COMBO_LIST_VALUE_CLS + "'>" + displayValue + "</span></li>");
          }`

2. Same goes for _**renderAheadList**_:

instead of:

`listHtml.push('<li value="' + value + '" class="' + isActive + '"><span class="' + FIELD_COMBO_LIST_VALUE_CLS + '">' + displayValue + '</span></li>');`

It sholud be:

`listHtml.push("<li value='" + value + "' class='" + isActive + "'><span class='" + FIELD_COMBO_LIST_VALUE_CLS + "'>" + displayValue + "</span></li>");`

Thanks,

**Comment by MikeTatsky** [comment]
Could you provide more details, please?
Your data consists from html?

**Comment by golanorbi** [comment]
With pleasure.
Yes, some of my data contains HTML tags which also contains attributes, those attributes would break because of the order of closing single quotes & double quotes.

For example:

I have a table column of Person.

When the list is like this:

`John Smith
Jack Ryan
Jason Lincoln
Frank Madison`

The multiselect combo filter works fine (the text in the table matches the text in the filter list).

However my list is presented in table column like this:

`<a href="/node/12345">John Smith</a>
<a href="/node/67890">Jack Ryan</a>
<a href="/node/54321">Jason Lincoln</a>
<a href="/node/09876">Jennifer Madison</a>
`
(I'd like the user to be able to click the person to see his/her full profile).

In this case the multiselect combo breaks because of the way the `<li>` of the multiselect combo filter is built.
If I inspect the first `<li>` of the filter I see the following render:

`<li value="<a href=" node="" 12345"="" class="" id="fancy-gen-49">John Smith" class=""&gt;<div class="fancy-field-checkbox-input" style=""></div><span class="fancy-combo-list-value"><a href="/node/12345">John Smith</a></span></li>
`
As you can see the `value` starts with `"`, and then since after the `href=` there's another `"` it basically closes the double quotes, and breaks the rest of the link, and since the link breaks it doesn't match the cell's content and then it won't filter anything.

I hope it is clear now. If you have any other questions, please let me know.

Thanks,

**Comment by MikeTatsky** [comment]
Thank you for details.
If data is presented with html tags then grid would work inccorect.
We advice you to add tag in `render` method.
https://fancygrid.com/api/config/columns/render

**Comment by golanorbi** [comment]
Thanks for the advice. I'm well aware of the `render ` method, and I use it for other different things.
Unfortunately, here I can't use it, because the links are generated on the fly through in the server side (mine is PHP).
(Of course, if I write them by myself I could definitely use the `render` method for that.).

In general, HTML tags are generated in the server side (Mine is PHP), and when they are in client they are already rendered, and there's nothing I can do about it.

Thanks.

**Comment by MikeTatsky** [comment]
Oh, I see.
Well, we will think how to resolve such cases.

**Comment by MikeTatsky** [comment]
You can modified loaded information before it will be applied to grid.
Please, study this data handler.
https://fancygrid.com/api/config/data/proxy/afterrequest

You can modify `o.response.data`.
You could remove html tag from server data.

**Comment by golanorbi** [comment]
Thanks for your answer.
It is a nice solution, however, my purpose is to **keep** the link to the Person's profiles.

Also, If I understand correctly, the inneHTML in the cell must match the innerHTML of the `<li>` in the filter (for the filter to work).
So, if I strip the HTML tags from the filter, and there are **still** HTML tags in the table cell (which I **do** want to keep, for the user to click on the link) then there won't be a match anymore and the filter will break.

i.e.
The innerHTML of the cell is still `<a href="/node/12345">John Smith</a>`
while the innerHTML after `value = value.replace(/<\/?[^>]+(>|$)/g, '')` will be `John Smith`, and there is the mismatch.

So, it's either to strip the HTML tags from both the cell, and the filter or keep them both.

And since we need the link, in order to keep them both, those double quotes and single quotes have to be switched (for the sake of the attributes of the HTML tags like `href` which starts with `"` and NOT with `'`) otherwise the `<li>` will end here:
`<li value="<a href="`

Different approach to fix this would be maybe, instead of switching between the quotes, maybe to escape them with a back slash.

In my humble opinion it is a bug. As a default, the user should be able to make table cell's text linkable without the need to do any kind of manipulation with the data.

Manipulation to the data should be for special cases, like conditional data, styling, formatting, and then the method `render` as well as the `data/proxy/afterrequest` should be definitely in use.

But maybe I'm wrong. So if you think the double quotes and the single quotes shouldn't be switched (or escaped) for those obvious cases then that's fine.

I do however **appreciate** your effort, and the very kind service.

**Comment by MikeTatsky** [comment]
I think the best and the simplest way to resolve it is the following.
You need to overwrite 2 methods after including library with your code.
`Fancy.Combo.prototype.renderList`
``Fancy.Combo.prototype.renderAheadList`

**Comment by MikeTatsky** [comment]
I close this ticket.
At the moment we can not insert default solution in code by some internal issue.
I hope that workarounds that we adviced will help.
