### ISSUE TITLE
HTML Tags in Table Cells Exported AS IS to Excel

### ISSUE THREAD

**Issue by golanorbi** [FancyGrid/FancyGrid#142]
Hi,

If a table cell contains HTML tags in it, the rendered content from rows is exported to Excel AS IS with its HTML tags.

So, if a table cell contains `<a href="https://www.abrahamlincoln.com">Abraham Lincoln</a>`;

the Excel will show `<a href="https://www.abrahamlincoln.com">`Abraham Lincoln`</a>`  in the cell,

Instead of its innerHTML `Abraham Lincoln`.

The problem seems to be in the grid.js file where the content of `column.exportFn` is checked.
The code takes the HTML content of the table AS IS and export it to excel, instead of EITHER rendering the content first OR exporting the innerHTML ONLY.

The fix is rather simple:

When exporting to Excel:

Instead of getting the row values AS IS, when exportFn is triggered, all HTML tags should be rendered/stripped.

So for stripping:

Instead of:

`var data = me.get(i),
                    value = me.get(i, column.index);`

It should be:

`var data = me.get(i);
            var html_value = me.get(i, column.index);
            var div = document.createElement('div');
            div.innerHTML = html_value;
            var value = div.textContent.trim() || div.innerText.trim() || "";`

AND THEN, at the end:

Instead of:

`rowData.push(me.get(i, column.index));`

It should be:

`rowData.push(value);`

Thanks,

**Comment by MikeTatsky** [comment]
Please, study this column property
https://fancygrid.com/api/config/columns/exportfn

**Comment by golanorbi** [comment]
I'm well aware of exportFn functionality which enables the user to alter the data before exporting to Excel.
And Yes. I did manage to alter the HTML tags manually, and strip them so I could get just the text (without the HTML tags) for the Excel file.

However, in my opinion, to begin with, it's not a normal behavior to export the HTML tags AS IS.
It doesn't make any sense to the user to get the content with the HTML tags rather than getting just the text in the Excel sheet.
Some simple users will find it hard to understand the HTML output AS IS, and it's not the desired result at the user's end. 
Maybe rendering the HTML tags to a complete styled content would make more sense.

If you think it's a normal behavior, please explain what you meant by referring me back to the API. I must have missed something.

Thanks.

**Comment by MikeTatsky** [comment]
Thank you for report.
We will restudy this issue.

**Comment by MikeTatsky** [comment]
Very good advice and report.
We will try to apply this in next release.

**Comment by MikeTatsky** [comment]
It just was done release with auto replacing html tags when export.
I close this ticket. If any problems with this issue then reopen this ticket, please.
