### ISSUE TITLE
server side filtering and pagination

### ISSUE THREAD

**Issue by vikas-29** [FancyGrid/FancyGrid#143]
I am using below version of fancygrid: 
1.7.142.
I have create a demo application which does server side filtering and pagination. I have followed below examples for reference:
1) Filter: https://fancygrid.com/samples/filtering/server
2) Pagination: https://fancygrid.com/samples/paging/server-paging.

I am using java with spring framework for server side logic.

My issue is when I do filtering, I get the correct response from the server. But pagination is getting scrolled to last page.
for example: If I am showing 400 rows in the grid with 10 rows per page, so there will be 40 pages initially . Then suppose I do filtering on some column and filtering result is 240 rows with 10 rows per page, now I will be having 24 pages. But when the grid is loaded with the filtered response the grid is scrolled to 24th page. I am expecting it to be on 1st page and not on 24th one.

Please provide me some solution for the same. 
thanks

**Comment by MikeTatsky** [comment]
We are sorry, it is bug of latest version.
 We did huge changes about state and could not catch this behavior on auto tests.

Thank you for the report.
We will try to fix it ASAP.

**Comment by MikeTatsky** [comment]
We just did fix-release.
We published on npm new version. GitHub will be updated later.

Also you can set behavior of page over flow.
https://fancygrid.com/api/config/paging/pageoverflowtype
