### ISSUE TITLE
F.Date.format(...) is invoked incorrectly

### ISSUE THREAD

**Issue by zsalkus** [FancyGrid/FancyGrid#146]
Hello, I have noticed in FancyGrid's source code that the function `F.Date.format` is invoked incorrectly. Its contract is `function(date, format, lang, mode)`, however, in some places it is invoked correctly, like the following line of code:
`F.Date.format(date, format.write, undefined, format.mode);` (grid.js:13333),
but in most places it is missing `lang` param and `format.mode` is passed as lang argument instead:
` F.Date.format(dateFrom, format.edit, format.mode);` (filter.js:1680).

I suggest to double check the usages and to fix the locations where the method is invoked incorrectly. My suggestion would be to swap `format.mode` and `lang` param places since lang param looks like optional.

**Comment by MikeTatsky** [comment]
Thank you for the report.
It looks like a bug but in fact it is just multi variants of invocation.
It should not cause bug in any grid configs.

**Comment by zsalkus** [comment]
Are you sure about that? I couldn't find an overload of `function(date, format, mode)`, so it means that every time when `format` is passed and `lang` is not, then `format` takes place of `lang` and mode itself is set to empty string. Correct me if I'm wrong.

**Comment by MikeTatsky** [comment]
@zsalkus 
The matter is `Fancy.Date.format` was supposed to use only internally.
If you need it, could you provide sample when it works incorrect, please?

"so it means that every time when format is passed and lang is not, then format takes place of lang and mode itself is set to empty string"
In this case lang will be taken `Fancy.i18n.en` and mode will be empty string.
If in grid it was provided i18n, for example `i18n: 'fi'` than it will take `fi` lang.
If you need to define mode, it accept only `sql` and date format will be like this `YYYY.mm.dd`.

If you plan to use it than such variant should work.
`Fancy.Date.format(new Date(), 'Y.m.d h:i:s');`

More examples:
`Fancy.Date.format(new Date(), 'YYYY.mm.dd', undefined, 'sql');`
`Fancy.Date.format(new Date(), 'YYYY.mm.dd', 'fi', 'sql');` //- It will work only if Finland lang was included.

**Comment by zsalkus** [comment]
> The matter is Fancy.Date.format was supposed to use only internally.
> If you need it, could you provide sample when it works incorrect, please?
> If you need to define mode, it accept only sql and date format will be like this YYYY.mm.dd.

Yes, it is used internally only. While testing out this grid I ran into an issue that the server side date filtering didn't work due to my computer's date format which is YYYY-mm-dd.
FancyGrid sends `%5B%7B%22operator%22%3A%22gteq%22%2C%22value%22%3A%22NaN%22%2C%22property%22%3A%22initiatedDate%22%7D%5D` which decodes into` [{"operator":"gteq","value":"NaN","property":"dateFrom"}]`. I looked into the source code and saw this incorrect invocation that I posted about. 
I have tried to fix the issue on my own and it worked, I had to modify one line and to delete one case statement from the filter.js processFilterValue function:
``` 
// change
splitted = value.toString().split(separator);

// delete         
case 'date':
  _value = new Date(Number(_value));
  break;
```

On top of that I added `undefined` to the format function invocation in order to make it work.

I am still unsure if it's a bug or some hidden feature that I am not aware about, but I was kinda sure that format was invoked incorrectly, that's why the issue was created.

**Comment by MikeTatsky** [comment]
As ASAP solution you can overwrite any method in Grid after it was included.
So you can add script with changed `Fancy.Date.format`.

Thank you for details. We will try to resolve it in next releases.

**Comment by zsalkus** [comment]
Okay. Also, I don't want to create a new issue, but copy/paste of the grid cell is not working on MacOS. On Windows it's okay. Perhaps you could take a look into that too?

**Comment by MikeTatsky** [comment]
@zsalkus 
We will study it. Thank you very much.
