### ISSUE TITLE
When filter data over server, focused field stays focused.

### ISSUE THREAD

**Issue by zsalkus** [FancyGrid/FancyGrid#148]
Hello, fancy grid v1.7.144 seems to have a bug fix called "When filter data over server, focused field stays focused.".

Use case:

- Table has a long cell, called _cb035f1b-fb8c-4bdd-8295-44bafaa23c5d_
- User tries to filter the data, types _cb_, forgets what to type next, looks into another screen and sees _035_, then wants to type the remaining text but focus is lost and has to click text field again.

Previously that was not the case. Perhaps this could be added as a feature toggle?

**Comment by MikeTatsky** [comment]
@zsalkus 
Thank for the report.
We will study it.

P.S.:
 Thank you very much for your previous report about Mac.
We detected several problems with it and we plan to fix it in future releases.

**Comment by zsalkus** [comment]
Should I close this issue then?

**Comment by MikeTatsky** [comment]
@zsalkus 
Do not close it, please.
We will close it by self when it will be resolved/fixed/answered.

**Comment by MikeTatsky** [comment]
@zsalkus 
We tried to replicate case but could not.
Could you provide screenshot/screencast, please?
If it is confidental than you can send us it on support email: support@fancygrid.com

**Comment by MikeTatsky** [comment]
We got this case.
It will be optional in next release.

**Comment by MikeTatsky** [comment]
@zsalkus 
Fix release was published.
No extra options are needed.
We improved current version to reset focus when loading done is finished.
