### ISSUE TITLE
Summary row and precision

### ISSUE THREAD

**Issue by matekhong** [FancyGrid/FancyGrid#149]
I've set default setting like this
` defaults: {
        type: 'number',
        precision: 2,
        summary: 'sum',
        render: function(o) {
            if (o.value === '0') {
                o.value = '';
            }
            return o;
        }
    }`
But it's not effect with Summary Row as below

![image](https://user-images.githubusercontent.com/17153200/105445839-7b1f3700-5ca3-11eb-8e66-e3a78fa5ca0a.png)

How could I set Summary row number format?

**Comment by MikeTatsky** [comment]
@matekhong 
Thank you for your question.

Add this property to grid config, please.

```
summary: {
  position: 'bottom'
}
```

Doc link:
https://fancygrid.com/api/config/summary/position

**Comment by matekhong** [comment]
@MikeTatsky 
Sorry, I mean the Total row showing format number is not same as other normal row
In the picture you can see that Normal row is showing [49,132.00] while Total row showing [49,132] (No decimal)

**Comment by MikeTatsky** [comment]
@matekhong 
Oh, I see.
It is bug, we will try to fix it in next release.

**Comment by matekhong** [comment]
Thanks!

**Comment by MikeTatsky** [comment]
@matekhong 
We published release with fix of this issue.
