### ISSUE TITLE
Fancygrid working incorrect with option 'valueKey' by combo column type

### ISSUE THREAD

**Issue by dreaming1402** [FancyGrid/FancyGrid#15]
Dear Sir,
Please help me fix this.
The option 'valueKey' not working with fancygrid combo type and is there my problem,

I have the column like that
![image](https://user-images.githubusercontent.com/22629505/28728339-7dce2094-73f2-11e7-982e-9762230e73aa.png)

This is html
![image](https://user-images.githubusercontent.com/22629505/28728357-91518b10-73f2-11e7-8150-018654d7e653.png)

My configs on javascript
![image](https://user-images.githubusercontent.com/22629505/28728426-d163afa8-73f2-11e7-8d71-035603ccf75c.png)

And the data response:
![image](https://user-images.githubusercontent.com/22629505/28728463-efce650a-73f2-11e7-92f9-e3f2abcd29cc.png)

**Comment by dreaming1402** [comment]
Hi, 
I see you are missing this code on line 28921 -> 28923,
Please fix it on next version.
Thank you
![image](https://user-images.githubusercontent.com/22629505/28729345-5b83be46-73f6-11e7-9117-56c9748c72d7.png)

Result:
![image](https://user-images.githubusercontent.com/22629505/28729466-bbfd13d0-73f6-11e7-86ba-cf7fdc986140.png)

![image](https://user-images.githubusercontent.com/22629505/28729454-b3ce7f1e-73f6-11e7-90ad-ff69066304c2.png)

**Comment by MikhailTatsky** [comment]
Please try this
```
columns: [{
...
},{
  index: 'state',
  title: 'State',
  type: 'combo',
  width: 110,
  displayKey: 'text',
  valueKey: 'value',
  data: {
    proxy: {
      url: 'states.json'
    }
  }
...

states.json
{
  "data": [{
    "value": "",
    "text": ""
  },{
    "value": "AL",
    "text": "Alabama"
  },{
    "value": "AK",
    "text": "Alaska"
  },{
    "value": "AZ",
    "text": "Arizona"
```

You wrote a bit wrong syntax.

**Comment by dreaming1402** [comment]
This is the options or bug?

I filtered 'Admin' like this but the fancygrid return both result
![image](https://user-images.githubusercontent.com/22629505/28729591-2ba64d32-73f7-11e7-83cf-982637cc3955.png)

**Comment by dreaming1402** [comment]
Hi Mr MikhailTatsky,

I'm sorry, please help me know what wrong syntax I got? I can see

**Comment by MikhailTatsky** [comment]
Sorry, I answered you wrong.
About reader I am not sure that we support it for combo.
I will check it out.

Let us do so:
I will try to solve it on weekends and provide you next-release version.

**Comment by dreaming1402** [comment]
Hi,
This ok, thank you for helpful.

Please help me answer the question above
![image](https://user-images.githubusercontent.com/22629505/28731520-76113bbe-73fe-11e7-9e6a-4a31db4ea7f6.png)

**Comment by MikhailTatsky** [comment]
It looks like bug.

**Comment by dreaming1402** [comment]
Yes, I got it.
Again, special thank you for helpful.

**Comment by MikhailTatsky** [comment]
You can download it here http://code.fancygrid.com/fancygrid-next.zip
Version 1.6.3

Note:
It was added `reader` for combo.
Also it was added strict search for combo.
We use text search(not value) for combo since grid contains only text and no way to search by value.

But this version was not tested, we did many code changes for this version so could be not stable.
We plan to release stable version on next weekends.

**Comment by MikhailTatsky** [comment]
We did official release with this fix.
