### ISSUE TITLE
Server side date issue

### ISSUE THREAD

**Issue by nickelbob** [FancyGrid/FancyGrid#150]
I believe this is suppose to be 

`value = '<=' + F.Date.format(dateTo, format.edit, format.mode);`

https://github.com/FancyGrid/FancyGrid/blob/22a3d1de3dd1bec5990606692f31cb0bbd8600df/src/js/widgets/grid/plugins/Filter.js#L1311

**Comment by nickelbob** [comment]
If you have server side filtering on a date column and try to just filter by dateFrom it'll fail because of this line.

**Comment by MikeTatsky** [comment]
Good day @nickelbob 
Thank you for the report.
We will study this issue and publish fix release on this weekend.

**Comment by MikeTatsky** [comment]
@nickelbob 
Thank you very much for the report.
We did fix-release with this solving issue.

**Comment by nicknjpconsultingllc** [comment]
@MikeTatsky No problem! Love the grid, thanks for building it!
