### ISSUE TITLE
Row copy working improperly

### ISSUE THREAD

**Issue by matekhong** [FancyGrid/FancyGrid#151]
When I selected multiple rows and use [Ctrl + C] some column didn't copied.

Here what I selected and copied
![image](https://user-images.githubusercontent.com/17153200/106562079-5c028e00-655c-11eb-8bfe-cd6a524c10d7.png)

Here what was my result
![image](https://user-images.githubusercontent.com/17153200/106562173-818f9780-655c-11eb-9ffb-ddab99beb88d.png)

It might caused by my data is in nested array as below
`var data = [{
    id: 34,
    accountname: 'YVL',
    projectname: 'YUWA_MA_Client_2020',
    enddate: '2021/07/31',
    country: 'Vietnam',
    yeardata: [1168.82, 1168.82, 1168.82, 1168.82, 1168.82, 1168.82, 1168.82, , , , , , ]
}, {
    id: 35,
    accountname: 'BBSV',
    projectname: 'BBSV_MA_2020',
    enddate: '2021/08/31',
    country: 'Vietnam',
    yeardata: [24702.50, 24702.50, 24702.50, 24702.50, 24702.50, 24702.50, 24702.50, 24702.50, , , , , ]
}];`

Is there any method to copy even value is in nested array?

**Comment by MikeTatsky** [comment]
@matekhong 
We will study this issue and answer today-tomorrow.

**Comment by MikeTatsky** [comment]
We studied issue.
We missed case with complex index-es for copy-paste.
It means that when you write column code like
```
},{
  title: 'March',
  index: 'year2015[2]',
  format: 'number'
},{
```
Index is complex and grid ignores it for copying.
We will try to resolve it in either this weekend and next weekend release.

As ASAP solution do not use complex indexes.
Change `yeardata: [1168.82, 1168.82, 1168.82, 1168.82, 1168.82, 1168.82, 1168.82, , , , , , ] ` to
`year2019may: 1168.82, year2019june: 1168.82, `
It is temporary solution.

**Comment by MikeTatsky** [comment]
@matekhong
Thank you very much for the report.
We did fix-release with this solving issue.
