### ISSUE TITLE
Still bug with valueKey by combo column type

### ISSUE THREAD

**Issue by vingrad** [FancyGrid/FancyGrid#16]
Unfortunately the last release (1.6.3) did not fix this bug. If you use both **displayKey** and **valueKey**, then the valueKey will be shown in the cell after value selection in combobox. Please fix.

**Comment by MikhailTatsky** [comment]
Thank you for the report.
We will recheck and answer soon.

**Comment by MikhailTatsky** [comment]
We detected several issues with **displayKey** and **valueKey**.
We will write ~30 tests specially for combo that avoid bugs with it in future.

Stable combo will be presented in version 1.6.4
We will write here when ready.

**Comment by MikhailTatsky** [comment]
We released new version 1.6.4
Please check it out.
`displayKey` and `valueKey` were simplified inside. 
We hope it will work now in all cases.

**Comment by vingrad** [comment]
Thank you very much. I will check this tomorrow.

**Comment by vingrad** [comment]
valueKey is ignored now.

**Comment by MikhailTatsky** [comment]
Yes, we did so that valueKey is ignored for filtering.
We realized that there is no sense in `valueKey` exactly for filtering and edit cell since data in column with combo has displayData.

The only one reasone to use valueKey for these cases if to send it on server for filtering.

**Comment by vingrad** [comment]
Should the valueKey be present at <li value="" ? There are no valueKey.

**Comment by MikhailTatsky** [comment]
Yes, it should contain value but from `displayKey`.
Could provide sample case when it does not have value?

**Comment by vingrad** [comment]
Yes, there are the value from the displayKey. But what is the reason then for the valueKey? 
I need to known which data are selected in combobox and submit their "id" => valueyKey to the server.

**Comment by MikhailTatsky** [comment]
We think we did mistake by providing `valueKey` for filtering and cell edit.
We see that almost not sense in it.

It should be used for forms only.

**Comment by vingrad** [comment]
valueKey is very useful for cell edit.

**Comment by vingrad** [comment]
I will to know which value has the user selected, not the name of the value, but a value.

**Comment by MikhailTatsky** [comment]
Could you please explain what is useful in `valueKey` for cell edit?
We for sure follow users needs.
We will try to return it back in 1.6.6.

**Comment by vingrad** [comment]
When using a cellTip it is also useful to have correct valueKey .

cellTip: '{title} sold {value}<br> items on {day}'

**Comment by MikhailTatsky** [comment]
I will close this issue.
If you have any questions about this feature please write us on email: support@fancygrid.com
We will definetly help you!
