### ISSUE TITLE
Sorting a grid by checkbox is not possible - Type select not handled

### ISSUE THREAD

**Issue by Kongolan** [FancyGrid/FancyGrid#165]
It's not possible to sort a grid if a checkbox is selected, it all gets ignored.

  ```
var columns = [
    {
      index: 'selected',
      title: 'Selection',
      type: 'select',
      headerCheckBox: true,
      width: 40,
      editable: true,
      locked: true, 
      sortable: true,
    },
]
```

later:
```
grid.sort('selected');
```

https://github.com/FancyGrid/FancyGrid/blob/master/src/js/data/mixins/Sort.js#L30
Shows that `type: select` is unhandled.

The sort algo for booleans is missing as well and should look like this:
```
   a.sort((a, b) => {
        // true values first
        return (a === b) ? 0 :  a ? -1 : 1;
    });
```

**Comment by Kongolan** [comment]
Can you fix it? We need that feature in production.

**Comment by MikeTatsky** [comment]
@Kongolan 
Could you provide your email, please?

We will add in you Slack.

It was not assumed that grid will be selected by this column type.
We need to know more how you will run sort over column header or over method `sort`.
We are not sure how enable this enchacement right, we need more details from you.

**Comment by Kongolan** [comment]
I want all checkboxes in the grid sorted to the top. So you can easily see what is selected in the grid. The column typ is `select` as shown above. I will sort over method and not over header.

**Comment by MikeTatsky** [comment]
@Kongolan 
We will try to do fix release on this weekend.

**Comment by MikeTatsky** [comment]
@Kongolan 
On npm it was published new version.
Please try
```
grid.sort('$selected', 'DESC');
grid.sort('$selected', 'ASC');
grid.sort('$selected', 'DROP')
````

Also you need
```js
selModel: {
  type: 'rows',
  memory: true
},
```

You do not need `index` for this column.

**Comment by Kongolan** [comment]
Looks good. I will test it and tell you, if it worked well. I think my costumer will be very happy!

**Comment by Kongolan** [comment]
It works fine. Thanks a lot, this is an appriciated solution!
