### ISSUE TITLE
Preselecting a Row

### ISSUE THREAD

**Issue by brettlandis** [FancyGrid/FancyGrid#166]
Is there a way to mark a row as selected WITHOUT triggering a selectRow event? I am attempting to store the selected rows in state and have them select/deselect without having an event fire.

Thanks!

**Comment by MikeTatsky** [comment]
@brettlandis 
Just did release with enabling this behavior.

You can use method `selectRow` like this

```js
grid.selectRow(1, true, true, false)
grid.selectRow(2, true, true, false)

grid.selectRow(7, true, undefined, false)
```

Last argument means do not fire select event.

**Comment by brettlandis** [comment]
Thanks so much!

**Comment by brettlandis** [comment]
Could you possibly update the JS files for the new version? I'm getting:

Loading failed for the <script> with source “https://cdn.fancygrid.com/@1.7.175/modules/dom.min.js?_v=17175”.

Thanks!

**Comment by MikeTatsky** [comment]
@brettlandis 
CDN was updated.
Sorry
