### ISSUE TITLE
cannot sort date column when mode is sql

### ISSUE THREAD

**Issue by benediktschlueter** [FancyGrid/FancyGrid#17]
I have a date column like this:

{
            index: 'TimeStamp',
            title: 'Judgement Day',
            type:'date', 
            sortable:true
            format: {
                read: 'yyyy-mm-ddTHH:MI:SS.u',
                write: 'yyyy-mm-ddTHH:MI:SS.u',
                edit: 'yyyy-mm-ddTHH:MI:SS.u',
                mode: 'sql'
            }
        }

When clicking on the column head to trigger sorting it throws error in function parse() line 5127
case 'T':
          if(mode === 'sql'){
            value = value.substr(1, value.length);
          }
          else{
            throw new Error('[FancyGrid Error] - Invalid date format: ' + format);
          }
          break;

because the property "mode" out of my columns format property is not getting into this method from getColumnOriginalValues.

**Comment by MikhailTatsky** [comment]
Thank you for the report.
We will try to fix it ASAP.

**Comment by MikhailTatsky** [comment]
We fix it in next release version 1.6.5 
You can try it here
https://code.fancygrid.com/fancygrid-next.zip

On case you do not know how to include files locally
here is link from doc: https://fancygrid.com/docs/getting-started/installation

**Comment by MikhailTatsky** [comment]
We released version `1.6.5` it contains fix of this bug.

Note:
We have one day cache so please clear cache.

**Comment by benediktschlueter** [comment]
Thanks very much, works now!
