### ISSUE TITLE
Web Page issue

### ISSUE THREAD

**Issue by elbelli2008** [FancyGrid/FancyGrid#172]
The page has not been working for a few days.
Does anyone know anything about this?

tks.

**Comment by MikeTatsky** [comment]
@elbelli2008 
Sorry for discomfort. 
Our development partner from New Zealand has let us down and is not communicating. 
We have in fact lost access to our domain. 
We will raise the site on the new domain [fancy-grid.com](https://fancy-grid.com)
It will take time. 
We hope that we will do it on this week.

**Comment by elbelli2008** [comment]
Hi, thanks for your quick reply! This new address work fine.

tks

**Comment by elbelli2008** [comment]
.
