### ISSUE TITLE
Web fancygrid documentation error

### ISSUE THREAD

**Issue by runnerktb** [FancyGrid/FancyGrid#174]
Please fixing web fancygrid.com, still error and can't open documentation

**Comment by MikeTatsky** [comment]
@runnerktb
Please, use https://fancy-grid.com

Sorry for the discomfort.
Our development partner from New Zealand has let us down and is not communicating.
We have in fact lost access to our domain.

If we can return our domain, it will work again on https://fancygrid.com

**Comment by runnerktb** [comment]
Owh okay @MikeTatsky, thanks you for answer my questin. hope your domain can be up again
