### ISSUE TITLE
Select box still active when click another row

### ISSUE THREAD

**Issue by OhnRazer** [FancyGrid/FancyGrid#176]
Hi @MikeTatsky i want to ask, very important to me.
It's possible that when selecting a select box in a table or editing a data row, the previous check option is not lost and remains selected?

thank you

**Comment by MikeTatsky** [comment]
@OhnRazer 
@OhnRazer
There are two types with checkboxes
Usual checkbox
https://fancy-grid.com/api/columns/checkbox

And for selection - `select`
https://fancy-grid.com/api/columns/select

Column `select`. It does not have `render` method.
In API there is not this option.
https://fancy-grid.com/api/columns/select

But column `checkbox` has it but it is limited.

In theory it is possible to do but it will be tricky and maybe it will be needed to use
grid events or controllers.
If you provide details describing all needed behavior, I could try to prepare a sample.

**Comment by OhnRazer** [comment]
yes i think can be use checkbox. but checkbox does not have select all in header.

actually in my case, i use type:select .when already select 1 data, then select row another data. my selection in first row not selected.
Is there an option when using type:select. 
Is the data I have selected not lost & still selected?

https://github.com/FancyGrid/FancyGrid/assets/5095341/e51bc661-e64e-4cf4-ad5f-effabcb5b145

**Comment by MikeTatsky** [comment]
@OhnRazer 
It seems to me you need this option.
https://fancy-grid.com/api/config/selmodel/checkonly

Also maybe you will need `memory` option
https://fancy-grid.com/api/config/selmodel/memory

**Comment by OhnRazer** [comment]
Awesome, thanks you very much @MikeTatsky it's work
