### ISSUE TITLE
CDN fancy grid down

### ISSUE THREAD

**Issue by runnerktb** [FancyGrid/FancyGrid#178]
Hi @MikeTatsky , 
something wrong with the https://cdn.fancygrid.com/. he always down 
"cdn.fancygrid.com’s DNS address could not be found. Diagnosing the problem."

**Comment by runnerktb** [comment]
okey i will try move to local server and download all modules.
thank you @MikeTatsky

**Comment by oblesh6** [comment]
Hello @runnerktb , 
Did you resolved this issue? 
If yes,  Could you please briefly explain it?

Thank you
