### ISSUE TITLE
cellTip: access to other properties of the cell object

### ISSUE THREAD

**Issue by vingrad** [FancyGrid/FancyGrid#18]
I need an access to all properties of the cell obejct in the cellTip function.

```
cellTip: function(o){
    if(!o.value){
      return false;
    }
    
    return o.value;
  }
```

With "o.value" I have only access to the value. Other properties such o.my_variable are undefined. It would be usefull to have in the cellTip function the second argument with the only cell object.

**Comment by MikhailTatsky** [comment]
Just tested.
If cellTip is `Function` than it sends all avaliable information.
Example:
```
cell: cellDom
column: columnObject
columnIndex: columnIndex
data: row data
e: Event
id: data row id
item: data row record
rowIndex: rowIndex
side: side
value: value
```

`o.my_variable` should be undefined.
Can you please clearify?

**Comment by vingrad** [comment]
Example:
```
{
  "data": [
    {"id": 1, "name": "Ted", "surname": "Smith"},
    {"id": 2, "name": "Ed", "surname": "Johnson"}
  ]
}
```

How can I access to the surname variable?  o.surname is undefined

**Comment by vingrad** [comment]
o.item.data does not contains the surname too.

**Comment by vingrad** [comment]
Sorry, this problem is only on combo-fields is present. I cannot get access to the valueKey-variable.

**Comment by vingrad** [comment]
Can you please check if the columnIndex is correct? I have columnIndex = 0, but this column has other string value index that I have defined.

**Comment by MikhailTatsky** [comment]
Checked combo and other types about cellTip.
data row avaliable in 2 ways.
1 - 
`o.data.surname`
2 - 
o.item.get('surname')

About `columnIndex`, it is order number.
If you need column of cell, it is avaliable in `o.column`
You can know it's index over `o.column.index`

Note:
We are thinking with team about valueKey.
Let us we try to solve your case without it?

**Comment by MikhailTatsky** [comment]
I will close this issue.
If you have any questions about this feature please write us on email: support@fancygrid.com
We will definetly help you!
