### ISSUE TITLE
Ajax demo files not load

### ISSUE THREAD

**Issue by ZeoNish** [FancyGrid/FancyGrid#180]
![image](https://github.com/user-attachments/assets/7153bc15-732c-4e8e-8613-806eaae0a530)
all demo .php files not load...

**Comment by MikeTatsky** [comment]
@ZeoNish 
Server side code was updated.
Now it should work.

**Comment by ZeoNish** [comment]
https://fancygrid.com/samples/filtering/server

![image](https://github.com/user-attachments/assets/6bd09b24-6894-4ce0-a4a6-dc3c3d7f9bac)

**Comment by MikeTatsky** [comment]
@ZeoNish 
Fixed
Thanks a lot
