### ISSUE TITLE
js npe error when using nativeScroller:true and expanding grid row

### ISSUE THREAD

**Issue by benediktschlueter** [FancyGrid/FancyGrid#19]
Hi there,
I set nativeScroller:true in my grid because the scrolling is much better. However now I get a js error whenever I doubleclick a row to expand it. There is no error when I set it to false so I believe its related to this.
Please see the attached debugger screenshot for all the details. Thx & regards!

Btw: Happens in 1.6.3 and 1.6.5 also

![bildschirmfoto 2017-08-20 um 03 57 22](https://user-images.githubusercontent.com/2990246/29491440-86e2c0ec-855c-11e7-8ac3-c0f3c968255f.png)

**Comment by MikhailTatsky** [comment]
Just fixed in next release version 1.6.6
You can try next version with this bug fix here
https://code.fancygrid.com/fancygrid-next.zip

On case you do not know how to include files locally
here is link from doc: https://fancygrid.com/docs/getting-started/installation

**Comment by MikhailTatsky** [comment]
It was done release of version 1.6.6 with this bug fix.
