### ISSUE TITLE
Grid not rendering

### ISSUE THREAD

**Issue by Protoneer** [FancyGrid/FancyGrid#2]
Hi.

I am trying to use FancyGrid with React to render about 10 small grids on a page.

Problem is that the Grids are not rendering the the changes after a Ajax call.

I have tried the update method with no luck. 

From console logging I can see the new data being retrieved, I can see that setting data on the grid is working. Yet, the screen does not update and I have tried update and load after setting the data.

Any clue what it might be?

**Comment by MikhailTatsky** [comment]
Hi.

Problem could be in data.
If you include jQuery on page than there is some issue.
jQuery process only strict json.
It means that if something like that:
`value: "Text"` or
```
"value": "Text 1",
"value2": "Text 2", // - not needed comma
```
Than it will not be processed.  
We are thinking about totally switch on self core exactly because of it.

So please check your data, it can be loaded ok but it will not be processed if it is not strict JSON.

**Comment by Protoneer** [comment]
Thanks for the quick reply. We really like this FancyGrids :)

I have tried your suggestions but it still does not seem to do it.

I have included a single html file example showing the problem.
It loads dataset 1 on start up and then when clicking the button should load dataset2.

Am I missing something?

`
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>DocumentStore</title>

    <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>


    
    <link href="http://cdn.fancygrid.com/fancy.min.css" rel="stylesheet">
    <script src="http://cdn.fancygrid.com/fancy.min.js"></script>
    <script>
        Fancy.MODULESDIR="http://cdn.fancygrid.com/modules/";
    </script>


</head>
<body>
    <div id="root"></div>
    <button id="btn">Click me</button>
    <script>
        var SMT_Time_config = {
            title: "SMT Time",
            width: 700,
            height: 300,
            theme: 'bootstrap',

            clicksToEdit: 1,
            defaults: {
                type: 'string',
                width: 75,
                resizable: true,
                sortable: true,
                editable: true
            },
            events: [{
                set: function(grid, o){
                    console.log(grid.getDataView());
                    state_data.SMTTime = grid.getDataView();
                }
            }],
            columns: [
                {
                    index: 'Date',
                    title: 'Date',
                    type: 'date',
                    format: {
                        read: 'd/m/Y',
                        write: 'd/m/Y',
                        edit: 'd/m/Y'
                    },
                    width: 100,
                    data: ["AAA","BBB","CCC"]
                },
                {
                    index: 'SetupStart',
                    title: 'SetupStart',
                    type: 'combo',
                    data: ["06:00","12:00","17:00"],
                    width: 100
                },
                {
                    index: 'SetupFinish',
                    title: 'SetupFinish',
                    type: 'combo',
                    data: ["06:00","12:00","17:00"],
                    width: 100
                },
                {
                    index: 'RunStart',
                    title: 'RunStart',
                    type: 'combo',
                    data: ["06:00","12:00","17:00"],
                    width: 100
                },
                {
                    index: 'RunFinish',
                    title: 'RunFinish',
                    type: 'combo',
                    data: ["06:00","12:00","17:00"],
                    width: 100
                },
                {
                    index: 'Total',
                    title: 'Total',
                    type: 'number',
                    width: 100
                },
            ]
        };


        var dataset1 =
                {"SMTTime":[
                    {
                        "Date": "01/06/2017",
                        "SetupStart" : "06:00",
                        "SetupFinish" : "06:00",
                        "RunStart" : "06:00",
                        "RunFinish" : "06:00",
                        "Total" : "1.25"
                    }]}

            ;

        var config = SMT_Time_config;
        config.data = dataset1.SMTTime;
        console.log(JSON.stringify(config.data));
        config.renderTo = "root";
        new FancyGrid(config);


        $("#btn").click(function(){
            var dataset2 =
                {"SMTTime":[
                {
                    "Date": "01/06/2017",
                    "SetupStart" : "12:00",
                    "SetupFinish" : "12:00",
                    "RunStart" : "12:00",
                    "RunFinish" : "12:00",
                    "Total" : "1.25"
                }]}
            ;

            var grid = FancyGrid.get("root");
            grid.data = dataset2.SMTTime;
            console.log(JSON.stringify(grid.data));
            grid.update();
        });
    </script>
</body>
</html>
`

**Comment by Protoneer** [comment]
In the example above the HTML elements are removed by

**Comment by Protoneer** [comment]
for some reason HTML code example does not play nice in comments so I uploaded the zipped HTML file.

**Comment by MikhailTatsky** [comment]
Give us one week, please.
All team is at client.

**Comment by MikhailTatsky** [comment]
In sample it is used not FancyGrid API.
To add data there are several methods.
https://fancygrid.com/api/methods/add
https://fancygrid.com/api/methods/insert

Also there are other methods that help to work with data.
We advice to read all avaliable methods.
https://fancygrid.com/api/methods
