### ISSUE TITLE
multi-line titles in column header not working ?

### ISSUE THREAD

**Issue by benediktschlueter** [FancyGrid/FancyGrid#20]
Hi there, I want to display column headers with a larger height because I have multiline titles or I cannot afford so much width for the longer column title. How can I do this? Longer titles are not automatically broken and the height stays for one line only.
If I patch css and set it 50px height the last row in the grid is not visible anymore which is not what I want also.

Thx for your help!

**Comment by MikhailTatsky** [comment]
Hi Benedikt,
Do you need to set height for columns header?
There are some properties about sizing in theming section.
For this case you need `cellHeaderHeight`.
All list of these properties is avaliable here
https://fancygrid.com/docs/design-and-style/themes

**Comment by benediktschlueter** [comment]
Works! Thx!
