### ISSUE TITLE
Bug: Expander + sorting removal error

### ISSUE THREAD

**Issue by Lazaroth** [FancyGrid/FancyGrid#24]
An opened expander isn't removed when a user sorts the table.

**Comment by MikhailTatsky** [comment]
Can you please provide some screenshots/code?
We can not replicate.

**Comment by Lazaroth** [comment]
Let me know if you also want code.

Images:
http://imgur.com/a/R0gfM

1. Unexpanded row
2. Expanded row
3. Sorting a column
4. The expanded row is still visible even though the row is gone.

**Comment by MikhailTatsky** [comment]
Yes, please provide code - still can not replicate.
Maybe you also do filtering or something else.

Could you please send your code on support@fancygrid.com that your data stays confidential.

**Comment by MikhailTatsky** [comment]
Fixed
