### ISSUE TITLE
Bug: Expanding causes selector to trigger

### ISSUE THREAD

**Issue by Lazaroth** [FancyGrid/FancyGrid#26]
When having both a type: 'expand' and type: 'select' in the same table, pressing the expand arrow also triggers the select. In my case this is unwanted behavior.

**Comment by MikhailTatsky** [comment]
We will do it as small feature.
Select if checkBox selection only.

**Comment by MikhailTatsky** [comment]
It was added in new release 1.6.8.
Here is documentation link.
https://fancygrid.com/api/config/selmodel/checkonly

Note:
Clear cache. We have 1 day cache.
