### ISSUE TITLE
Ability to change selector for 'id' in grid data

### ISSUE THREAD

**Issue by ybdiel** [FancyGrid/FancyGrid#27]
Hello, 
As far as i can tell my data when using a REST API must contain a field named 'id' in order for that to be used in the PUT/DELETE methods for the relevant actions.
Would be good to have a way of the selector of that.
For example use 'productId' for the id field

**Comment by MikhailTatsky** [comment]
Good day.
In grid all data is based on index `id`.
We would not recommend to change this name to another.
But we will try to provide such ability in one nearest releases.

**Comment by MikhailTatsky** [comment]
@ybdiel, 

Could you please connect with us over support@fancygrid.com about this issue?

**Comment by ybdiel** [comment]
Hello, i used allFields: true and took a different approach
Thanks a lot
