### ISSUE TITLE
server paging can not be worked fine

### ISSUE THREAD

**Issue by swust-xiaoj** [FancyGrid/FancyGrid#31]
I follow [this example](http://jsfiddle.net/gh/get/jquery/1.9.1/FancyGrid/FancyGrid-Samples/tree/master/jsfiddle/grid/paging/server-paging),but repalce my url and root. [this demo](https://fancygrid.com/samples/paging/server-paging) can work.what can I do for my code.

**Comment by MikhailTatsky** [comment]
Please take a look at this php sample
https://github.com/FancyGrid/FancyGrid-Samples/blob/master/php/paging.php

**Comment by swust-xiaoj** [comment]
tks!
My json data didn't have `totalCount`  param, sorry for that.
And I have another problem, that is how to modify `data.proxy.url` to rerender the datagrid. I don't find some method to solve it.

**Comment by MikhailTatsky** [comment]
Add this to paging, please.
https://fancygrid.com/api/config/paging/refreshbutton
Than refresh button will be added in bar
https://fancygrid.com/samples/paging/server-paging

**Comment by swust-xiaoj** [comment]
Maybe I have to manually click refresh button to rerender in this way. I prefer to select some params, and click button named `search`  to rerender table.
So I define a global variable in workspace, destroy and renew it every click `search`, using `grid.destroy()`.
Haha...
Anyway, many thanks for your reply.
👍

**Comment by MikhailTatsky** [comment]
There is also not documented method
```
grid.refresh();
```

We will add in doc soon.

**Comment by swust-xiaoj** [comment]
Is there  some method to modify `data.proxy.url` ?

**Comment by MikhailTatsky** [comment]
There is method.
But you can do this.
```
grid.store.proxy.api.read = 'new.php';
```

**Comment by swust-xiaoj** [comment]
That's great!!!
thanks again
