### ISSUE TITLE
how to set table head style

### ISSUE THREAD

**Issue by swust-xiaoj** [FancyGrid/FancyGrid#32]
There has api to set columns style ,like below code
```
.photo img {
  width: 80px;
  margin-top: -5px;
  margin-left: -10px;
}
...
columns: [{
  type: 'image',
  title: 'Photo',
  index: 'src',
  width: 80,
  cls: 'photo'
},{
...
```
but, I set column width, and table head text is too long to overflow.
so , how can I newline the text?
Thanks

**Comment by MikhailTatsky** [comment]
Could you please do screenshot?
Do you have problem with title of grid or with column title?

**Comment by swust-xiaoj** [comment]
like this   ![image](https://user-images.githubusercontent.com/9254851/31809981-9d3cc7d6-b5ac-11e7-8c92-ff6d6454f49b.png)

**Comment by MikhailTatsky** [comment]
I am afraid that 100% working varient does not exist at the moment.
You can use html in title.
```
cellHeaderHeight: 60,
columns: [{
  title: 'A<br>B<br>C<br>',
  ...
```

We will learn this issue and try to find some solution.

**Comment by swust-xiaoj** [comment]
![image](https://user-images.githubusercontent.com/9254851/31811666-f599321a-b5b2-11e7-85fc-47d2f63c5117.png)
I have tried the above way,the head height has increased,but the text did not work fine.
Thank you.
Looking forward to your solution
