### ISSUE TITLE
Qquery

### ISSUE THREAD

**Issue by D0Gmatist** [FancyGrid/FancyGrid#35]
Please tell me how to add additional parameters to the query
![image](https://user-images.githubusercontent.com/8296952/32143517-7c84741a-bcbb-11e7-8a12-1566cccaf392.png)

**Comment by MikhailTatsky** [comment]
At the moment setting params work partly over `data.proxy.params` (not in all cases)
```
data: {
  proxy: {
    params: {
      n: 1,
      text: 'text'
    }
  }
}
```
Give us 1-2 days please we will improve it and do next release.

**Comment by D0Gmatist** [comment]
`data: {
  proxy: {
    params: {
      n: 1,
      text: 'text'
    }
  }
}`

What would work so much you need to make changes here

![image](https://user-images.githubusercontent.com/8296952/32144412-6cd1710e-bcc9-11e7-87e9-49b77ff9f8df.png)
change

![image](https://user-images.githubusercontent.com/8296952/32144422-a448b93a-bcc9-11e7-8d78-c550ed8329fa.png)

**Comment by MikhailTatsky** [comment]
We just did release with this improvement.
Version 1.6.15

Doc link:
https://fancygrid.com/api/config/data/proxy/params
Please check it out.

Note:
Clear cache, we have 1 day cache.

**Comment by D0Gmatist** [comment]
![image](https://user-images.githubusercontent.com/8296952/32146347-1f9075fc-bce7-11e7-84fb-dec7ceae225f.png)
(((

**Comment by MikhailTatsky** [comment]
Sorry, for sorting does not work.
We will try to fix it ASAP.

**Comment by MikhailTatsky** [comment]
Try again, please.
We will not update github and npm.
Just loaded changes on cdn.

Note:
Again time clear cache, please.

**Comment by D0Gmatist** [comment]
FIX ))

![image](https://user-images.githubusercontent.com/8296952/32146567-582c3c72-bcea-11e7-94fd-f7d57252a7f9.png)

**Comment by MikhailTatsky** [comment]
Do you have problem with displayKey and valueKey for combo filter?
If no, it is better do not change it.

The matter is we in past added `displayKey` and `valueKey` but realized 
it should be used only for forms.
For grid it has several not clear situations.

**Comment by D0Gmatist** [comment]
![image](https://user-images.githubusercontent.com/8296952/32146698-82b473f4-bcec-11e7-9d8f-b1b4ebfe4f97.png)
![image](https://user-images.githubusercontent.com/8296952/32146710-9e382b20-bcec-11e7-99b7-aa0833284759.png)
![image](https://user-images.githubusercontent.com/8296952/32146722-cda30f88-bcec-11e7-9356-005d453b630b.png)
If you remove the fix, it does not work **valueKey: 'id',**

**Comment by MikhailTatsky** [comment]
Ok, I see.
But at the moment we can not apply it to release because than
it will appear bugs with editing and some varients of filtering.
If this fix works for you, it is good.

To be honest, we do not know what to do with this situation.
`displayKey` with `valueKey` works very bad for grid.
It is good only for form combo.
We had big discussion about it and can not find good solution.
