### ISSUE TITLE
Подскажите пожалуйста

### ISSUE THREAD

**Issue by D0GB0G** [FancyGrid/FancyGrid#36]
![image](https://user-images.githubusercontent.com/33227862/32177946-8bd48b76-bd9c-11e7-873f-5121944b3617.png)
![image](https://user-images.githubusercontent.com/33227862/32177983-9fbf3730-bd9c-11e7-83d2-a5c0ca946773.png)
![image](https://user-images.githubusercontent.com/33227862/32178056-d9839a6a-bd9c-11e7-9ed0-837acce8bf43.png)

В чем может быть моя ошибка? 
**Заранее спасибо!**

**Comment by MikhailTatsky** [comment]
Could you please show part of code about theming?

**Comment by D0GB0G** [comment]
![image](https://user-images.githubusercontent.com/33227862/32178390-a0598456-bd9d-11e7-87bf-905f3809879e.png)

**Comment by MikhailTatsky** [comment]
Strange.

Can not replicate.
Give us a bit time(about hour).

**Comment by D0GB0G** [comment]
Thank you so much )

**Comment by MikhailTatsky** [comment]
Change theme to this.

```
theme: {
  name: 'default', // or other theme name.
  config: {
    ...
  }
},
```

Date picker can not read theme from grid and generates bug.

**Comment by D0GB0G** [comment]
Cool ... ))

**Comment by MikhailTatsky** [comment]
Good :)
