### ISSUE TITLE
Mini bug

### ISSUE THREAD

**Issue by D0Gmatist** [FancyGrid/FancyGrid#37]
I found a mini bug
Two columns
1 column) menu - true
2 column) menu - false

if you swap, dragging the column
the menu remains in place

**Comment by MikhailTatsky** [comment]
Can not replicate.
 Could you please do screencast?
JING is good free tool for screencasts
https://www.techsmith.com/jing-tool.html

**Comment by D0Gmatist** [comment]
https://www.screencast.com/t/IaxshrC3GBJA

**Comment by MikhailTatsky** [comment]
Thank you for the bug report and screencast.

**Comment by MikhailTatsky** [comment]
Sorry for very delayed answer.
It looks like this bug was fixed in one of releases.
