### ISSUE TITLE
Date column NaN-NaN-NaN 0NaN:NaN:NaN

### ISSUE THREAD

**Issue by D0GB0G** [FancyGrid/FancyGrid#38]
![image](https://user-images.githubusercontent.com/33227862/32213334-de553cf8-be2b-11e7-85e4-dd9d39e108da.png)
Hello!
Tell me please.
Why is not the date and time displayed?
Date and time format - 2017-10-11 13:49:56
![image](https://user-images.githubusercontent.com/33227862/32213422-34fca348-be2c-11e7-8804-7357998eb0e8.png)
Thanks in advance

**Comment by MikhailTatsky** [comment]
It occured after past release?
Did it work before?

**Comment by MikhailTatsky** [comment]
You have mistake in date format.

`h` is for 12-hour format of an hour with leading zeros, values: 01 to 12
You need to use `H` for your case.
`H` is for 24-hour format of an hour with leading zeros, values: 00 to 23

We follow PHP's date() function formats.
http://php.net/manual/en/function.date.php

**Comment by D0GB0G** [comment]
Thank you

**Comment by MikhailTatsky** [comment]
You are welcome ;)
