### ISSUE TITLE
Row not added when deleting 2 rows before

### ISSUE THREAD

**Issue by MarintheJerome** [FancyGrid/FancyGrid#39]
I can reproduce the bug here : https://fancygrid.com/samples/edit/cell

Basically I add a row by clicking on "Add", then I remove 2 rows (not the one i just added) by selecting them and clicking on "Remove". 
I then click on "Add" and nothing happens.

**Comment by MikhailTatsky** [comment]
Thank you very much for reporting bug.
We will fix in next release.

Next release planned on the end of week.

**Comment by MikhailTatsky** [comment]
Fix is avaliable in in next release version, you can access it right now.
https://code.fancygrid.com/fancygrid-next.zip
Do not forget to set Fancy.MODULESDIR to local path of FancyGrid modules.
Example: Fancy.MODULESDIR = '/fancygrid/modules/';

Official release with this fix will be on weekends.

**Comment by MikhailTatsky** [comment]
Release with bug fix was done

**Comment by MikeTatsky** [comment]
@Pritamthing you need to add code `Fancy.MODULESDIR='fancygrid/modules/'` after import or include library.
For example.
```
<script src="https://cdn.fancygrid.com/fancy.min.js"></script>
<script>
Fancy.MODULESDIR='fancygrid/modules/'
</script>
```

For React
```
import { Fancy, Grid } from 'fancygrid-react';
Fancy.MODULESDIR='fancygrid/modules/'
```

Also you can import modules.
```
import { Fancy, Grid } from 'fancygrid-react';

import 'fancygrid/client/modules/sort.min';
import 'fancygrid/client/modules/dom.min';
import 'fancygrid/client/modules/edit.min';
import 'fancygrid/client/modules/grid.min';
import 'fancygrid/client/modules/selection.min';
import 'fancygrid/client/modules/menu.min';
import 'fancygrid/client/modules/exporter';
import 'fancygrid/client/modules/excel.min';
```
