### ISSUE TITLE
Full height

### ISSUE THREAD

**Issue by MirlanBekturov** [FancyGrid/FancyGrid#4]
Hi, how i can set full or responsive height of grid?

**Comment by MikhailTatsky** [comment]
The only you need is that width/height would be not set.
And that html element(in which you render grid) has right responsive css.
I think this doc could useful.
https://fancygrid.com/docs/grid-concepts/sizing

Here is sample:
http://jsfiddle.net/gh/get/jquery/1.9.1/FancyGrid/FancyGrid-Samples/tree/master/jsfiddle/grid/miscellaneous/responsive
