### ISSUE TITLE
OAuth2 support 

### ISSUE THREAD

**Issue by ybdiel** [FancyGrid/FancyGrid#41]
Hello, is OAuth supported in FancyGrid? I cannot find anything on the documentation (so far at least) . 
I have a use case where i have to retrieve data from a secured REST API and i need to provide a valid token (which i get myself from the relevant identity server) 

If it's not supported it would be good if we could do something like:
```
data: {
  proxy: {
    type: 'rest',
    url: 'app.php/users',      
    token: 'xxxxxx'
    }
}
```
or even
``` 
data: {
  proxy: {
    methods: {
      create: 'POST',
      read: 'POST', 
     ...
    },
    api: {
      create:  { 
         url: 'new.php', 
         token: 'xxxx' 
     },
      read: { 
         url: 'load.php',
        token: 'yyyy'
      }
     ...
    }
  }
}
```
Because there are some scenarios that you need to provide different tokens containing different claims to get access to different methods

Thanks alot

**Comment by MikhailTatsky** [comment]
At the moment OAuth2 is not presented.
Thank you for feature request.
We will try to add it in nearest future.

**Comment by ybdiel** [comment]
Alternatively maybe it would be possible to modify the headers of the ajax calls? Then we can pass the tokens ourselves and also support scenarios that require accept header versioning etc

**Comment by MikhailTatsky** [comment]
You can set headers.
Please take a loot at doc link
https://fancygrid.com/api/config/data/proxy/headers

**Comment by MikhailTatsky** [comment]
Sorry for very delayed answer.
We thaught about enabling OAuth2 as feature.
We decided that this feature is not needed for our commercial clients.
