### ISSUE TITLE
AJAX (dynamic content)

### ISSUE THREAD

**Issue by D0GB0G** [FancyGrid/FancyGrid#42]
Found problems with AJAX (dynamic content)
https://www.screencast.com/t/iGJuPQ9GbgVv

https://www.screencast.com/t/lwIxZ7gwruec

**Comment by MikhailTatsky** [comment]
About second video I got bugs, thank you for reporting.
About first one, I am sorry I did not get what is the problem.

**Comment by D0GB0G** [comment]
in the first there is a cell prompt.
In the second video, the hint is also visible

**Comment by MikhailTatsky** [comment]
Oh, thank you. I got it.

**Comment by MikhailTatsky** [comment]
Please try next release version
https://code.fancygrid.com/fancygrid-next.zip

Note:
It is not official release that is why please set 
`Fancy.MODULESDIR = '/fancygrid/modules/';` or use full build
