### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by D0GB0G** [FancyGrid/FancyGrid#44]
In the table, there are no records. The server appeared on the server.
Making grid.refresh ()
It does not take place on the server.

I reload the page, there is 1 row in the table
A record 2 is added to the database
Making grid.refresh ()
I'm running on the server.

https://www.screencast.com/t/mj8pudKm8h

**Comment by MikhailTatsky** [comment]
Thank you for the report.
Please write you email, we will add you in Slack.

**Comment by D0GB0G** [comment]
375256232834@yandex.by

**Comment by MikhailTatsky** [comment]
Invitation sent.
Did you get it?

**Comment by D0GB0G** [comment]
+

**Comment by MikhailTatsky** [comment]
Fixies are avaliable in pre-release version.
