### ISSUE TITLE
Export to CSV

### ISSUE THREAD

**Issue by MikhailTatsky** [FancyGrid/FancyGrid#46]
Export data from grid to CSV file

**Comment by MikhailTatsky** [comment]
It will be available in release 1.7.24
Doc methods: `getDataAsCSV` and `exportToCSV`

**Comment by laidick** [comment]
can it export all data from the model instead of just the rows in paging?

**Comment by MikhailTatsky** [comment]
@laidick 
 At current stage it exports only visually displayed data.
Thank you for the note, we will add option to export all data in next release.

**Comment by laidick** [comment]
Great thanks

**Comment by MikhailTatsky** [comment]
@laidick 
Just did release with discussed option.
https://fancygrid.com/api/methods/exporttocsv

**Comment by laidick** [comment]
You are amazing !

**Comment by danilopaulinodasilva** [comment]
> @laidick
> At current stage it exports only visually displayed data.
> Thank you for the note, we will add option to export all data in next release.

When I filter the data using date a column and try to export to CSV, I got the CSV file with the correct number of lines, but not the visually displayed data. 

Is this suppose to happen?

**Comment by MikhailTatsky** [comment]
@danilopaulinodasilva 
 It is not like it should work.
Could you provide us your sample case, please?
We can not replicate this behavior.

**Comment by danilopaulinodasilva** [comment]
@MikhailTatsky glad to hear that

You can see in action here: http://the-ybox.tech/fancygrid-filterdate.php
No sensitive data, make yourself confortable to test.

Basically when you filter by 04/01/2019 to 04/30/2019 you will get 404 registers. And when you export to CSV, you will get 2018 registers and something like that.

But will come 404 lines in CSV as well.

**Comment by MikhailTatsky** [comment]
@danilopaulinodasilva
Page asks to login.
Maybe you can provide sample on jsfiddle?

**Comment by danilopaulinodasilva** [comment]
Sorry about that, free access now :)

**Comment by MikhailTatsky** [comment]
@danilopaulinodasilva 
 It is since options `all: true`.
But without this option, it will send to export only data on displayed page but
it requires to export data all pages.
We will try to improve and provide in next release(approximately on this weekend).

**Comment by danilopaulinodasilva** [comment]
@MikhailTatsky wow, thats it!! It works! 

I can live with that until is done and keep waiting, thanks anyway.

**Comment by MikhailTatsky** [comment]
;)
