### ISSUE TITLE
Altering the contents of a specific action cell item

### ISSUE THREAD

**Issue by ybdiel** [FancyGrid/FancyGrid#50]
Hello,
How can i alter the contents of a specific action cell either on data binding or afterwards ? 
I have a use case that i want to display a delete button only on the grid items that can be deleted.

I've tried a column definition of 
```
{
	type: 'action',
	width: 65,
	items: [{
		text: '<i class="fa fa-times fa-2x" aria-hidden="true"></i>',
		action: 'remove',
		render: function(o) {
			if (o.data.canDelete) {
				return o;
			}
			return "";
		}
	}]
}
```
but without any luck.  I am now trying to get the contents of a specific cell after binding a custom function on the grid 'update' event but no luck there so far either.

Could you advice? 

Alternatively i can do it like this: 

```
function removeDelete(grid) {

  var selector = '.fancy-grid-column-action-item';

   grid.each(function(item) {
	if (!item.data.canDelete) {
		var cell = $(selector)[item.$index];
		$(cell).html("");
	}
  });
}
```

but i am hoping there is a better way.

**Comment by MikhailTatsky** [comment]
Could you please write your email on support@fancygrid.com?
We will add you in Slack to get issue better.

**Comment by MikhailTatsky** [comment]
Please try next release version.
https://code.fancygrid.com/fancygrid-next.zip

```
{
  type: 'action',
  width: 65,
  items: [{
    text: '<i class="fa fa-times fa-2x" aria-hidden="true"></i>',
    action: 'remove',
    render: function(o) {
      if (o.data.canDelete) {
	return o.value = '';
      }
      
      return o;
    }
  }]
}
```

**Comment by MikhailTatsky** [comment]
Fixed
