### ISSUE TITLE
Grid does not show properly in a bootstrap tab when no fixed width is set

### ISSUE THREAD

**Issue by cmodiano** [FancyGrid/FancyGrid#51]
Hi,

I have many fancy grids in bootstrap tabs. When I use a fixed width the grid is correctly displayed. When I does not set the width to make the grid fill the container size, it remains hidden when the tab shows.

**Comment by MikhailTatsky** [comment]
Could you please write your email?
We will add you in Slack to get issue.

**Comment by cmodiano** [comment]
I made my address public

**Comment by MikhailTatsky** [comment]
Good :)
Invitation was sent.

**Comment by MikhailTatsky** [comment]
Problem was in bootstrap tabs.
If tab is hidden and grid is responsive than grid can not detect width and set it to 0 as result 
grid is not visible on tab activation.
It is fixed in next version 1.6.24.
It will be avaliable soon.
