### ISSUE TITLE
Bug: searching doesn't work when expander uses another FancyGrid object in its render function

### ISSUE THREAD

**Issue by Sarithis** [FancyGrid/FancyGrid#52]
I've found a pretty nice example of how to add another FancyGrid to an expanded row in your [documentation](https://fancygrid.com/api/config/expander/render). It works, but it breaks the search functionality of the parent grid. Check out [this fiddle](https://jsfiddle.net/LLwqnkyo/). Try to use the search field, then expand one row and use the search field again - it will stop working after a row is expanded.

**Comment by MikhailTatsky** [comment]
Thank you for the bug report.
We will try to provide fix in next release(on weekends).

**Comment by MikhailTatsky** [comment]
Fixed.
Please try pre-release version
https://code.fancygrid.com/fancygrid-next.zip

Include file `fancy.full.min.js` for fast checking that it works.
