### ISSUE TITLE
Error when rowEdit = true and column Expand is present

### ISSUE THREAD

**Issue by PaoloNardini** [FancyGrid/FancyGrid#54]
An error occur when a column is present with type: 'expand'  and rowEdit is set to true. I tried to set the expand column not editable with editable: false but doesn't help. Removing the expand column the edit works well. Any tip?
Error is: "Cannot set property 'value' of undefined'.

**Comment by MikhailTatsky** [comment]
Thank you for the report.
We will try to fix it ASAP.
Note: it's not supposed that rowexit and rowexpander will be used together but required we will enable it.

**Comment by MikhailTatsky** [comment]
Fixed in next release version.
If you need it ASAP please download pre-release version
https://code.fancygrid.com/fancygrid-next.zip
And include full build for fast checking that it works.
`fancy.full.min.js`

To use `fancy.min.js` you need set 
`Fancy.MODULESDIR = '/fancygrid/modules/'`

**Comment by PaoloNardini** [comment]
Thank you, I have tried the pre-release and it works!
I know that it's not supposed to be used together, but I need to make the whole row and the expanded section editable separately.
