### ISSUE TITLE
Incorrect calls of Date.format

### ISSUE THREAD

**Issue by Novik** [FancyGrid/FancyGrid#56]
Parameter 'lang' is skipped, you should to pass ```undefined``` as third parameter:

https://github.com/FancyGrid/FancyGrid/blob/master/src/js/widgets/grid/elements/mixins/BodyUpdater.js#L1678
https://github.com/FancyGrid/FancyGrid/blob/master/src/js/widgets/grid/plugins/Filter.js#L820
https://github.com/FancyGrid/FancyGrid/blob/master/src/js/widgets/grid/plugins/Filter.js#L821
https://github.com/FancyGrid/FancyGrid/blob/master/src/js/widgets/grid/plugins/Filter.js#L831
https://github.com/FancyGrid/FancyGrid/blob/master/src/js/widgets/grid/plugins/Filter.js#L841
https://github.com/FancyGrid/FancyGrid/blob/master/src/js/widgets/grid/plugins/RowEdit.js#L729

Something strange here, IMHO we need only 2 parameters in this call:

https://github.com/FancyGrid/FancyGrid/blob/master/src/js/widgets/picker/Date.js#L548

**Comment by MikhailTatsky** [comment]
Can you please provide a peace of your code with grid?
Or maybe screencast if possible (Jing is good to do screencast).

Jing - https://www.techsmith.com/jing-tool.html

**Comment by Novik** [comment]
Sorry, but I haven't time for this. But IMHO bugs is obvious.
In all these places we have calls like
```F.Date.format(date, format, mode)```
but corresponding prototype looks like
```
Fancy.Date = {
...
format: function(date, format, lang, mode)
```

**Comment by MikhailTatsky** [comment]
Sorry for late answer.
It is not bug, `format` method apply both 3 and 4 params.
Depending on number of params different behavior.

So it is not bug.
