### ISSUE TITLE
Incorrect date parsing/formatting

### ISSUE THREAD

**Issue by Novik** [FancyGrid/FancyGrid#57]
IMHO we not need a second parameter here:

https://github.com/FancyGrid/FancyGrid/blob/master/src/js/core/types/Date.js#L194
https://github.com/FancyGrid/FancyGrid/blob/master/src/js/core/types/Date.js#L212
https://github.com/FancyGrid/FancyGrid/blob/master/src/js/core/types/Date.js#L220

We need 1) dateTo instead dateFrom here 2) as I already told, parameter ```lang``` is skipped in this call
https://github.com/FancyGrid/FancyGrid/blob/master/src/js/widgets/grid/plugins/Filter.js#L841

**Comment by MikhailTatsky** [comment]
Ok, thank you.

We need a bit time to learn issue.

**Comment by MikhailTatsky** [comment]
Answered in previous issue.
It is not bug.
Method `format` applies both 3 and 4 params.

**Comment by Novik** [comment]
Very strange, but on your wish.
Just for interest, on this fragment we also have "not a bug"? ;)))
I mean 'dateFrom' instead 'dateTo' in the last line...

```
      else if (isValid2) {
        if (isRemote !== true) {
          value = '<=' + Number(dateTo);
        }
        else {
          value = '<=' + F.Date.format(dateFrom, format.edit, format.mode);
```

**Comment by MikhailTatsky** [comment]
Do you have real bug in your app with that?
We can not detect any bugs about it, we need more information.
