### ISSUE TITLE
Double encoding in case of server filtering

### ISSUE THREAD

**Issue by Novik** [FancyGrid/FancyGrid#58]
Here

https://github.com/FancyGrid/FancyGrid/blob/master/src/js/data/mixins/Filter.js#L220

we have call to ```encodeURIComponent```.
IMHO this call is redundant, because we already have encoding in the jQuery ajax call (processData is true in the ajax settings).
As result, all filter parameters have double encoding when they are passed to the server.

**Comment by MikhailTatsky** [comment]
FancyGrid can be used without jQuery.
We will learn this issue.

**Comment by MikhailTatsky** [comment]
Fixed.
