### ISSUE TITLE
The number of pages is not calculated after calling the FancyGrid update function

### ISSUE THREAD

**Issue by Sarithis** [FancyGrid/FancyGrid#59]
When you set the data parameter to an empty array and then use the add() or setData() functions to manually add some data to a grid, the paging bar doesn't update - it shows that there's just one page when in fact there should be more of them. Calling the update function doesn't help. The only workaround I've found is to call the setPageSize function - then the number of pages is calculated properly.
The problem occurs in both 1.7.5 (the latest release) and 1.6.20 (the version I'm currently using).

[**Fiddle**](https://jsfiddle.net/4covkh3j/1/)

Code:
```
/* Data for the grid */
let companies = [];
for (let i = 0; i < 100; i++) {
    companies.push({
        name: "name",
        id: i
    });
}

let grid = new FancyGrid({
    title: `Companies`,
    renderTo: `container`,
    width: 450,
    height: 300,
    data: [],
    paging: {
        pageSize: 5 //100 / 5 = 20 pages
    },
    events: [{
        init: function(grid) {
            grid.setData(companies);
            grid.update(); //Now the grid should have 20 pages, but it has only one
            //grid.setPageSize(5); //Uncomment this to recalculate the number of pages
        },
    }],
    columns: [{
        index: `name`,
        type: `number`,
        title: `Company`,
    }, {
        index: `id`,
        type: `number`,
        title: `ID`,
    }]
});
```

**Comment by MikhailTatsky** [comment]
It is bug.
Thank you for the report.
As ASAP bug fix, do this.
After `grid.update();` add
```
grid.store.calcPages();
grid.paging.updateBar('bbar');
```

**Comment by MikhailTatsky** [comment]
Just released version with this bug fix.
