### ISSUE TITLE
Bug everywhere

### ISSUE THREAD

**Issue by Nosforever** [FancyGrid/FancyGrid#6]
This plugin is beatiful but is very bugged.
Every day i found one or more bugs.
Grouping, filter and set together not work well.

**Comment by MikhailTatsky** [comment]
We are sorry.
We do not have enough money to hire devs and to do project more stable.

**Comment by MikhailTatsky** [comment]
Could you please write bugs in issues that you found, please?
It will help us much to improve product.

**Comment by MikhailTatsky** [comment]
We did big fix release.
We did big focus on filter and grouping.
Could you be so kind to check on bugs required functionality?
