### ISSUE TITLE
There is no "File upload function"??

### ISSUE THREAD

**Issue by GGoMoong** [FancyGrid/FancyGrid#60]
FancyGrid is very good module. But I need file upload function.
FancyGrid doesn't support this function??
Any development plan??

**Comment by MikhailTatsky** [comment]
You can include core library file.
```
<script src="https://cdn.fancygrid.com/fancy.min.js"></script>
```

Than when you run FancyGrid for FancyForm, all modules will be autoloaded.
Even css file.

**Comment by GGoMoong** [comment]
Oh, you seem to misunderstand my needs.
I want to use file uploading function in Grid cell. I wish to attach file for each row.

There is no description of File upload in the FancyGrid's document.

**Comment by MikhailTatsky** [comment]
Which data type would you like to upload in grid?
Excel, CSV or other?

**Comment by GGoMoong** [comment]
Maybe Excel, PDF, images(jpg,gif,etc,.)

**Comment by MikhailTatsky** [comment]
As I got you need `exportTo` functionality.
At the moment, we support export to Excel.
https://fancygrid.com/api/methods/exporttoexcel

You can add button in some one bar.
https://fancygrid.com/docs/grid-concepts/bars
And in button handler run method to export to Excel.

Road Map:
We plan during 1 month to add Export to CSV.
About PDF - we did not study issue.
About to image - we did not study issue, but afraid it could be complex and timely.

**Comment by GGoMoong** [comment]
I mean "Upload".
I want to upload files to server through FancyGrid.
NOT EXPORT NOT DOWNLOAD!!

**Comment by MikhailTatsky** [comment]
I am terribly sorry.
Maybe you have some sample from other products?

**Comment by GGoMoong** [comment]
https://editor.datatables.net/examples/advanced/upload.html

Just like this sample or "inline file upload"

**Comment by MikhailTatsky** [comment]
Thank you for the link.
To be honest this feature will not appear soon unless some commercial client will ask for it.

**Comment by MikhailTatsky** [comment]
I am sorry for very delayed answer.
We thaught about this feature, it requires to provide cloud service from us that to enable this feature.
We do not plan to add this feature.
