### ISSUE TITLE
Column width units

### ISSUE THREAD

**Issue by ybdiel** [FancyGrid/FancyGrid#62]
Hello,
Would be really good if we could do i.e. width: '220px', width: '10%' instead of just width: 220 on column declarations

**Comment by MikhailTatsky** [comment]
There is property flex for columns.
It works similiar to percents.
https://fancygrid.com/api/config/columns/flex

**Comment by ybdiel** [comment]
Works nice, but if you resize grid that column can even disappear while the others set with width remain the same and you can scroll. 
Is there a way to set min-width ? and flex the rest?

**Comment by MikhailTatsky** [comment]
Could you please do screencast?

Jing is good and free tool for screencasts.
https://www.techsmith.com/jing-tool.html

**Comment by ybdiel** [comment]
Sure, sent an email to support containing the captured video.

**Comment by MikhailTatsky** [comment]
We answered you by email.
It needs to export video to cloud free site and provide us link.

P.S.:
If you like we could add you in Slack for Trial Support.

**Comment by MikhailTatsky** [comment]
You can try minWidth for column in pre-release version
https://cdn.fancygrid.com/fancygrid-next.zip

Official release will be provided on weekends.
