### ISSUE TITLE
remoteFilter: false fails when remotePage:true

### ISSUE THREAD

**Issue by ybdiel** [FancyGrid/FancyGrid#63]
When i enable remotePage then also automatically remoteSort and remoteFilter get enabled. I set em explicitly back to false but although i can disable remoteSort and will work with local data, disabling remoteFilter causes the search to stop working with error:
```
fancy.js:3500 Uncaught TypeError: Cannot read property 'id' of undefined
    at constructor.changeDataView (fancy.js:3500)
    at constructor.updateStoreSearches (filter.min.js?_v=178:1)
    at constructor.search (filter.min.js?_v=178:1)
    at constructor.search (grid.min.js?_v=178:1)
    at fancy.js:7515
```
my settings are 
```
data: {
	remoteSort: false,
	remotePage: true,
	remoteFilter: false,
		proxy: {
			type: "rest",
			url: API_ENDPOINT + '/codes/packages',
			reader: {
				root: "items"
			}
		}
},
```

**Comment by MikhailTatsky** [comment]
I am afraid it is not possible to use `remoteSort: false` and `remoteFiltert: false` with `remotePage: true`.

**Comment by ybdiel** [comment]
remoteSort:false works with remotePage: true , just the filtering . But anyway was planning to implement remote filtering on my app later on.. might as well do it now
