### ISSUE TITLE
Align does not work for action type columns

### ISSUE THREAD

**Issue by ybdiel** [FancyGrid/FancyGrid#64]
Hello, found a minor issue: 
The following column definition does not seem to apply the alignment. Tried at both column and item level 
```
{
title: 'Delete',
type: 'action',
align: 'center',
width: 100,
items: [{
  text: 'X',
  action: 'remove',
  align: 'center'
 }]
}
```

**Comment by ybdiel** [comment]
I've just read about cellAlign , doesn't seem to apply either

**Comment by MikhailTatsky** [comment]
Action column items are for custom elements.
It is expected you will write css by self.

Take a look at this sample.
https://fancygrid.com/dashboards/autosave-false/
```
},{
  type: 'action',
  width: 65,
  items: [{
    text: 'Delete',
    cls: 'action-column-remove',
    action: 'remove'
  }]
}]
```
