### ISSUE TITLE
Angular support

### ISSUE THREAD

**Issue by nul0m** [FancyGrid/FancyGrid#65]
Do you have a working example? The [plunker example of FancyGrid with Angular 2](https://plnkr.co/edit/jgII7k)  from your [Docs](https://www.fancygrid.com/docs/getting-started/angular2) does not work.

**Comment by MikhailTatsky** [comment]
Thank you very much for reporting.
CDN urls on Angular site are not available, we will learn how to fix it.

**Comment by MikhailTatsky** [comment]
Here is link on workable sample https://plnkr.co/edit/Ze4eIU
We did not update doc section yet since we are out of time at the moment.

Again time thank you for letting us know.
