### ISSUE TITLE
Column type 'date' fails when there is no value

### ISSUE THREAD

**Issue by ybdiel** [FancyGrid/FancyGrid#66]
When using a column type 'date' and the API returns no value (i.e nullable dates) the grid fails.
I have a use case for example that i am getting data for 'OrderDate' and 'DeliveryDate' and delivery date is returned null from the API if the item has not been delivered.

**Comment by MikhailTatsky** [comment]
Thank you, we will recheck it.

**Comment by MikhailTatsky** [comment]
Let me advice you to try this.
If your normal value is '09/12/1971' than not data is ''.
It is not allowed to use `null` or `undefined` as values.

**Comment by ybdiel** [comment]
A nullable datetime is a valid object in C# and Microsoft's WebAPI2 (that the grid is connected to) serializes it as null so i can't really do much about it. I tried omitting the value completely hoping it will default to '' but the grid still fails. 
Is there maybe an option i can pre-process the data before they bind to the grid? So i could convert the null to '' there?

**Comment by MikhailTatsky** [comment]
Ok, we will try to enable it.

**Comment by MikhailTatsky** [comment]
It was fixed in latest release 1.7.37
I am sorry for so long time to fix.
It has low priority.
