### ISSUE TITLE
the i18n not work

### ISSUE THREAD

**Issue by zhaobingss** [FancyGrid/FancyGrid#67]
the i18n not work

**Comment by MikhailTatsky** [comment]
Could you please provide more information?
Language module loads from `Fancy.MODULESDIR`.
If set this property wrong than it will not work.

**Comment by zhaobingss** [comment]
@MikhailTatsky thanks now it works,but how can i set the cell nowrap,you konw sometimes the content is so long and i dont't wan't ellipsis. thank you very much.

**Comment by MikhailTatsky** [comment]
May I ask you for new bug/question to do new issue, please?
I will close this thread since it looks like all questions were solved.
