### ISSUE TITLE
Passing Variable to FancyGrid Column config "Hidden" Not Working

### ISSUE THREAD

**Issue by adityaheaptrace** [FancyGrid/FancyGrid#69]
columns: [{
									index: 'tableSchema',
									title: 'Table Schema',
									flex: 1,
									align: "center"
								},{
									index: 'tableName',
									title: 'Table Name',
									flex: 1,
									align: "center"
								},{
									index: 'fullyQualifiedName',
									title: 'Fully Qualified Name',
									flex: 1,
									align: "center"
								},{
									index: 'isRoot',
									title: 'Is Root',
									type: 'checkbox',
									hidden: 'genericAdapter',
									flex: 1
								}

genericAdapter here is a value from the arrays of data i am sending to fancy grid. 
data[i].genericAdapter
tried a independent typescript variable with 
this.GenericAdapter still no go .

**Comment by MikhailTatsky** [comment]
`hidden` can have value `true/false` and it can not be written from data.
https://fancygrid.com/api/config/columns/hidden

**Comment by adityaheaptrace** [comment]
Ok 
But then how do i show columns dynamically/ based on a condition??

**Comment by MikhailTatsky** [comment]
You should detect it before init `new FancyGrid`
If you have something specific and can not do it before init than there is method `hideColumn`.
https://fancygrid.com/api/methods/hidecolumn

**Comment by adityaheaptrace** [comment]
Ok fixed it !!
So it did work for data 
that.booleanData
Thanks for the help !!!

**Comment by MikhailTatsky** [comment]
Glad to help.
