### ISSUE TITLE
How to filter from date... till date... format on fancygird using fancyform?

### ISSUE THREAD

**Issue by dreaming1402** [FancyGrid/FancyGrid#7]
Please help me one problem.

I want to filter the date column on fancygrid like from date ... till date ... using field in fancyform.
I see the sample can filtering the ages from... to... but I can do with date format.
I try to convert the date format to number using Date.getTime () like the header filter but it not working. Only operator '=' and no convert can using on this.

Please help me, thank you

**Comment by MikhailTatsky** [comment]
Are you searching for this?
https://fancygrid.com/dashboards/employee/

**Comment by dreaming1402** [comment]
Yes, but I want to filter the date by field in form have 2 field from... and to... like date column

**Comment by dreaming1402** [comment]
I also debug the event from form and grid filtering, please check it by link below:
https://drive.google.com/open?id=0B0DVYu2uLfPMeFpLcll6akhvcnc

**Comment by MikhailTatsky** [comment]
It is bug thank you for the report.

**Comment by MikhailTatsky** [comment]
For fast fix do this after including library
```
Fancy.Grid.prototype.addFilter = function(index, value, sign){
    var me = this,
      filter = me.filter.filters[index],
      sign = sign || '';

    if(filter === undefined){
      filter = {};
    }

    if(Fancy.isDate(value)){
      filter['type'] = 'date';
      filter['format'] = this.lang.date;
      value = Number(value);
    }

    if(value === ''){
      delete filter[sign];
    }
    else{
      filter[sign] = value;
    }

    me.filter.filters[index] = filter;
    me.filter.updateStoreFilters();
  };
```
Send to addFilter date value as date!!!

Here is example
```

var dateFilterFromFn = function(field, value, oldValue){
  var grid = FancyGrid.get('grid');
  
  grid.addFilter('birthday', Fancy.Date.parse(value, 'm/d/Y'), '>=');
};

var dateFilterToFn = function(field, value, oldValue){
  var grid = FancyGrid.get('grid');
  
  grid.addFilter('birthday', Fancy.Date.parse(value, 'm/d/Y'), '<=');
};

new FancyForm({
  renderTo: 'form',
  title: 'Filter Form',
  width: 300,
  height: 185,
  defaults: {
    type: 'date'
  },
  items: [{
    label: 'Date from',
    type: 'date',
    name: 'datefrom',
    events: [{
      change: dateFilterFromFn
    }]
  },{
    label: 'Date to',
    name: 'dateto',
    type: 'date',
    events: [{
      change: dateFilterToFn
    }]
  }]
});
```

**Comment by dreaming1402** [comment]
So this function Fancy.Date.parse(value, 'm/d/Y') will return date value: 12/24/2017?

My return is 'Sun Dec 24 2017 00:00:00 GMT+0700 (SE Asia Standard Time)' and it is string type,
I try with new Date(value) to make it is correct the condition 'if(Fancy.isDate(value)) {}'

Again, filter['format'] it not work for me because the default format not same my form field format
: format:{read:'Y-m-d', write:'d-m-Y', edit:'Y-m-d'}
So I try to change filter['fortmat'] like this:
    filter['format']['read'] = "Y-m-d";
    filter['format']['write'] = "d-m-Y";
    filter['format']['edit'] = "Y-m-d";

and it working.

So I think 2 problem with new fix:
1. The Fancy.Date.parse() function it return string type and not correct with condition 'if(Fancy.isDate(value)) {}'
2. The default 'this.lang.date' it not working if I custom the date format

This fix will be available on new version, Sir?

**Comment by MikhailTatsky** [comment]
We will add fix in next release.

**Comment by dreaming1402** [comment]
Thank you so much :+1:

**Comment by MikhailTatsky** [comment]
It was done

Please read comment in issue https://github.com/FancyGrid/FancyGrid/issues/9
