### ISSUE TITLE
how to change row background color

### ISSUE THREAD

**Issue by zhaobingss** [FancyGrid/FancyGrid#70]
how to change row background color ? please.

**Comment by MikhailTatsky** [comment]
If change theme styling than over css like this.
https://jsfiddle.net/fancygrid/zud2L5rm/

If change color depending on cell values than requires to use property render.
https://fancygrid.com/api/config/columns/render
https://jsfiddle.net/fancygrid/bmj74L42/

There are variety varients about styling for example
https://fancygrid.com/dashboards/heatmap-pollution/

Also possible to define self theme but it is very complex
https://fancygrid.com/docs/design-and-style/themes

**Comment by jesal-bhowmick** [comment]
doesn't work with checkbox
https://jsfiddle.net/bmj74L42/30/

**Comment by MikhailTatsky** [comment]
@jesal-bhowmick 
It was done release with fix.
