### ISSUE TITLE
Bug in pagination

### ISSUE THREAD

**Issue by Junglefish** [FancyGrid/FancyGrid#71]
I have been evaluating a number of js-based grids for a project I am working on. I like many of the features of FancyGrid but I noticed a bug in your pagination code.

Please see your example page here: https://fancygrid.com/samples/paging/pagesize

The legend at the bottom that reads "Rows 1 - 21 of 22" should read "Rows 1 - **20** of 22". You can see this error better if you alter the records-per-page to 5, in which case you can see that the legend reads "Rows 1 - 6 of 22", "Rows 6 - 11 of 22", etc. Each of the upper digits is simply one-too-high.

Can you give feedback as to when this bug might be fixed?

Thanks,

**Comment by MikhailTatsky** [comment]
Oh.
Thank you for the report.
We will fix it on this weekend release.

**Comment by MikhailTatsky** [comment]
It was fixed in pre-release version.
You can download it here
http://cdn.fancygrid.com/fancygrid-next.zip

Official release will be available at this weekend.

**Comment by Junglefish** [comment]
Hi Mikhail

Impressed by your fast turnaround! :-)

I'm using the CDN service right now while I'm evaluating. Will that be fixed over the weekend?

**Comment by MikhailTatsky** [comment]
On CDN version 1.7.35.
Fixed version is 1.7.36.

Yes, CDN will be updated with version 1.7.36 at this weekend.

**Comment by MikhailTatsky** [comment]
It was loaded latest release on CDN.

Note:
I wrote you wrong about version number.
Latest version is 1.7.35
Clear cache hard to use latest version from CDN.
