### ISSUE TITLE
grid.setColumnTitle(index.'nameiwant') is not working

### ISSUE THREAD

**Issue by aditya777hp** [FancyGrid/FancyGrid#72]
Uncaught TypeError: myGrid.setColumnTitle is not a function    zone.js:195

**Comment by MikhailTatsky** [comment]
Methods are not available after code of grid if you are using this way to include library
`<script src="https://cdn.fancygrid.com/fancy.min.js"></script>`
You need to choose one of approach
1 - Include full build
`<script src="https://cdn.fancygrid.com/fancy.full.min.js"></script>`

2 - Run methods after grid will be inited.
Please read https://fancygrid.com/docs/grid-concepts/methods
Grid needs time to load modules and methods are different modules.
For short
```
var grid = new FancyGrid({
  ...,
  events: [{
    init: function(gridInstance){
      grid.setColumnTitle(...);
      //Or
      this.setColumnTitle(...);
      //Or
     gridInstance.setColumnTitle(...);
    }
  }],
  ...
});
```

Note:
 You have mistake in arguments `index.'nameiwant'`
Please view doc link for samples.
https://fancygrid.com/api/methods/setcolumntitle

**Comment by aditya777hp** [comment]
I am calling the method after the grid is initialized using the grid reference in the same place the title bar reference method i am calling, which BTW works 

myGrid.setColumnTitle('customIcon', 'Restore'); //this is not working 

TitlebarGrid.tbar[i].hide(); //(this works

**Comment by MikhailTatsky** [comment]
Could please write you email here on in support chat?
We will include you in Slack and our dev will look your case over TeamViewer.

**Comment by aditya777hp** [comment]
Ok thanks for the initiative but I will have to take permission 
Please give me a some time !!

**Comment by MikhailTatsky** [comment]
If you like you can view on live sample.
It change email column title.
https://jsfiddle.net/fancygrid/sfdo5qrw/

**Comment by MikhailTatsky** [comment]
By the way there is one more way to change column title.
If you set column property `titleEditable: true` and double click on column than
you could change it over text field.
https://fancygrid.com/api/config/columns/titleeditable

**Comment by aditya777hp** [comment]
cool 
Ok but then how do you change the column title in the HTML using the script tag
Something like this !!


<script src="https://cdn.fancygrid.com/fancy.min.js"></script>

<div id="container"></div>

<script>
	container.setColumnTitle('email', 'Work Email');
</script>

**Comment by MikhailTatsky** [comment]
If you only start learning than include full build for simplicity.
`<script src="https://cdn.fancygrid.com/fancy.full.min.js"></script>`
```
<script>
var grid = new FancyGrid({
  ...
}):
...
grid.setColumnTitle('email', 'Work Email'); 
</script>
```

**Comment by aditya777hp** [comment]
Ok I tried something !!
What changed do you suggest ???
If you can please join !!
https://jsfiddle.net/sfdo5qrw/12/#&togetherjs=ce8z7IxsJk

**Comment by MikhailTatsky** [comment]
So, is now ok?

**Comment by aditya777hp** [comment]
I understood whats happening but then i want to call the method after the dom has loaded .
I tried using the grid.update() method  for this but that dint work.

**Comment by aditya777hp** [comment]
and I am using the grid in angular 4

**Comment by MikhailTatsky** [comment]
Let us try Slack and TeamViewer if it is possible.
It will be much faster.

**Comment by MikhailTatsky** [comment]
You can add id for grid and get grid from any place.
```
new FancyGrid({
  id: 'myGrid',
  ...
});

....
function someFunc(){
  var grid = Fancy.getWidget('myGrid');

  grid.setColumnTitle(...);
}
```
