### ISSUE TITLE
Headers for combo

### ISSUE THREAD

**Issue by kkange** [FancyGrid/FancyGrid#74]
hi
combo widget config

data: {
              proxy: {
                reader: {
                  root: 'data'
                },
                url: 'http://localhost:2424/plum/v1/code?q=place',
                headers: { authorization: 'Bearer ' + this.$auth.token() }
              }
            }

headers not working  check plz

**Comment by MikhailTatsky** [comment]
Headers are not presented for combos.
Maybe it is better to try `params` with method `POST`?

```
data: {
  proxy: {
    reader: {
      root: 'data'
    },
    url: 'http://localhost:2424/plum/v1/code?q=place',
    headers: {
      authorization: 'Bearer ' + this.$auth.token() 
    }
  }
}
```

**Comment by kkange** [comment]
ok thank you
