### ISSUE TITLE
Grid with null dates fails even after replacing with ''

### ISSUE THREAD

**Issue by jesal-bhowmick** [FancyGrid/FancyGrid#76]
error shown - a.getFullYear is not a function
Is this a hack? if so, where do I edit?
https://stackoverflow.com/questions/43963447/fancy-grid-date-type

**Comment by MikhailTatsky** [comment]
We fixed this issue.
The date values could be both `null` and `''`.
Maybe you use old version, upgrade to latest, please.

**Comment by jesal-bhowmick** [comment]
Does not work with server data + editable
https://jsfiddle.net/o90L7rd5/27/
