### ISSUE TITLE
howto compile without angular, vue?

### ISSUE THREAD

**Issue by devzonetrack** [FancyGrid/FancyGrid#79]
howto compile without angular, vue?

**Comment by devzonetrack** [comment]
That i mean without angular, vue and chart module to reduce size? coz some time we no need those modules

**Comment by MikhailTatsky** [comment]
Angular, React and Vue wrappers are not modules so they are not in build.
About other modules if you include `fancy.min.js` it will load all used modules by self dynamicly.
So you do not need to worry about size.
The only one issue about modules, it is better to set where from library will load modules like this.
```
<script src="your_path/fancygrid/fancy.min.js"></script>
<script>
Fancy.MODULESDIR = 'your_path/fancygrid/modules/';
</script>
```
If you will not set `Fancy.MODULESDIR` all modules will be loaded from our CDN.
