### ISSUE TITLE
How to index data into header filter combo type (fancygrid)

### ISSUE THREAD

**Issue by dreaming1402** [FancyGrid/FancyGrid#8]
How to make the multiple index data auto put in multiple header filter combo type for user choice by json data
Not by manual and just by Fancygird function

Thank you!

**Comment by MikhailTatsky** [comment]
Currently it is absent.
It is in our todo list.

**Comment by dreaming1402** [comment]
Thank you for your answer, I'm waiting for that

**Comment by MikhailTatsky** [comment]
In next release version 1.6.5 we added multi filtering for combo.
You can try it here 
https://code.fancygrid.com/fancygrid-next.zip

**Comment by MikhailTatsky** [comment]
We released version `1.6.5` it contains this feature.
Check it out in this sample
https://fancygrid.com/dashboards/default/

Note:
We have one day cache so please clear cache.

![multi-filter](https://user-images.githubusercontent.com/1744857/29353622-86542e72-8273-11e7-8b8c-2ed10d5806ea.png)
