### ISSUE TITLE
Having One Combo set the Data for Another Combo

### ISSUE THREAD

**Issue by surfcoders** [FancyGrid/FancyGrid#81]
On a FancyForm, how can I change the "data" property on a combo dynamically when selecting the value of another combo?  For example, I have a combo called "Regions", and another called "Branches".  I want the user to select a Region, then populate the "Branches" combo with all the branches for the selected region.

I'm sure there is a way to do it, but went through the documentation and couldn't find it.  Maybe I missed it.

Thanks as always.

Nelson @ SurfCoders

**Comment by MikhailTatsky** [comment]
Good day Nelson.
Here is sample
https://jsfiddle.net/fancygrid/25uqcxdw/

And useful doc link
Study methods
https://fancygrid.com/apiform/fields/combo
