### ISSUE TITLE
Trying to use the local language as the "simplified Chinese" is troublesome.

### ISSUE THREAD

**Issue by pololipo** [FancyGrid/FancyGrid#82]
Trying to use the local language as the "simplified Chinese" is troublesome.Now just use the fancyform control as an example.
尝试使用选择本地语言为'中文简体'的时候遇到的麻烦，现在仅仅是使用fancyform控件为例
Use international configuration: i18n:'zh-CN'，but the effect is frustrating。Is there anyone else's practice?
使用了国际化配置: i18n:'zh-CN'，但是效果不好，有没有其他人解决过同样问题的实践？
我试过fancygrid和fancyform，中文效果都不好
![zh-cn1](https://user-images.githubusercontent.com/26294780/48682664-50795580-ebe4-11e8-9e46-c3cf15033cfb.jpg)
1、Head select month block，the line was changed and exceeded the block.
 头部选择月份的块换行，且年份超出块的范围
2、The name of the week did not show complete.
 星期的名称没有显示完整
3、Underline "today" wrap and exceed block range.
下方的‘当天’换行，且超过块范围

![zh-cn2](https://user-images.githubusercontent.com/26294780/48682683-7141ab00-ebe4-11e8-9a16-da742365d5db.jpg)
4、Select month interface and do not display the corresponding Chinese name.
选择月份界面并没有显示对应的中文名称

![zh-cn3](https://user-images.githubusercontent.com/26294780/48682844-43a93180-ebe5-11e8-9cbe-ebfa0745bf4e.jpg)
5、Trying to use the  configuration  ‘ lang’ ,but....
尝试过使用‘lang‘配置，效果一样的不理想

I need help!

**Comment by MikhailTatsky** [comment]
Thank you for the bug report.
We will study it and try to fix in next release(in 1-2 weeks).

**Comment by MikhailTatsky** [comment]
Here is ASAP solution.
It is pre-release version with fix of this bug.
https://cdn.fancygrid.com/fancygrid-next.zip

**Comment by MikhailTatsky** [comment]
Try one the following
1 full build - `fancy.full.min.js`
2 Set `Fancy.MODULESDIR` to your local path.
```
Fancy.MODULESDIR = 'your_path/fancygrid/modules/';
```

At the moment you include core file that load modules from our CDN with old version.
If you won't help connect over support@fancygrid.com 
We will include you in Slack and our engineer will help you over TeamViewer.

P.S.:
 Thank you very much for the report of these bugs we did not have tests on it and we found some extra issues with i18n.

**Comment by pololipo** [comment]
Yes,Set **Fancy.MODULESDIR** to the local path,and modify the configuration in the local language file(zh-CN.js) ，it works.

In my test project,I fix these issues by adjusting the CSS Style。Maybe after more study, I will try to imitate fancy's style to modify; of course, I look forward to better fancy.

**Comment by MikhailTatsky** [comment]
It was done official release with fix of all these issues.
