### ISSUE TITLE
Multiples Summary?

### ISSUE THREAD

**Issue by natxocc** [FancyGrid/FancyGrid#83]
Is it possible to have multiple summary on same column?
In docs seems not to appear how. If I put several summarys only see last one. For example, show average, sum, max and min at the same time.

Thanks.

**Comment by MikhailTatsky** [comment]
Thank you for the question.
Do you mean possibility to change summary from `sum` to `average` and so on over some UI element?
Or do you mean to summary rows at the same time on top and bottom?

**Comment by natxocc** [comment]
I refered to second question (several summary rows and one for avg, other, for sum...), but you first answer is also a good option.
When you have large datasets it's very usefull to have some calculated values (Max, Min, Avg... )

**Comment by MikhailTatsky** [comment]
We already work on "sum to average and so on over some UI element".
If all will be good it will be in one of next release.

![image](https://user-images.githubusercontent.com/1744857/49516050-a23f0280-f8a9-11e8-87f9-0c6cf3839177.png)

**Comment by MikhailTatsky** [comment]
It was released new version with this feature.
Please try https://fancygrid.com/api/config/summary/options
Try it and be welcome to write feedback.
