### ISSUE TITLE
Select and Copy text ?

### ISSUE THREAD

**Issue by emailagece** [FancyGrid/FancyGrid#84]
Dear Fancygrid,

I'm new comer here, i read api documentation but cannot find what i looking for. My case is to enable select and copy text from grid, how to do that ?

Btw sorry my english is not good.

Thank you

salam

**Comment by MikhailTatsky** [comment]
Good day.
Thank you for your question.

Selection is very big issue.
It could be done in many ways.
There are `cell`, `cells`, `row`, `rows`, `column`, `columns` selections.
For `row` and `rows` there are some extra things like memory selection.
Here is tutorial and screencast.
https://fancygrid.com/tutorials/getting-started/selection
https://scrimba.com/p/pbWvaSa/cJQVVUN

To copy selected cells/rows you can use CTRL+C and contextmenu
https://fancygrid.com/api/config/contextmenu

**Comment by emailagece** [comment]
Awesome @MikhailTatsky thank you so much, this textSelection: true is great too. Fancygrid is very good @MikhailTatsky 

salam
