### ISSUE TITLE
Check for invalid fields

### ISSUE THREAD

**Issue by surfcoders** [FancyGrid/FancyGrid#85]
Is there a way (method or event) to check if a field on a form is invalid?  I've set up the correct vtype but I need to check if any fields are invalid before saving/updating.

Also, is there a way to pre-set an invalid field when opening the form?  For example, I am presenting a form to add a new record, and most of the fields are empty, but required.  I'd like to pre-set them with the invalid field css.

Thanks

Nelson @ SurfCoders

**Comment by surfcoders** [comment]
I found a workaround for question #1 using jQuery:

`               
if ($('.fancy-field-not-valid')[0]) {
    // Invalid fields detected
} else {
   // No invalid fields detected
}
`
But it would be nice to have a built-in method.

Still looking for your advice on the second question

**Comment by surfcoders** [comment]
Sorry, closed the issue by accident

**Comment by MikhailTatsky** [comment]
Using jQuery for solving this question is not good.
Let me advice you method `form.valid();`
For form items like this `form.items[2].isValid();`
It is not documented, we will add it in doc in next release.

About second question, you can run method `form.valid();` on init event for form and it will mark fields as invalid.

**Comment by MikhailTatsky** [comment]
We updated doc.
Added info to fields and validation section for form.
