### ISSUE TITLE
I want to return to the previous value of a cell if result from service is false.

### ISSUE THREAD

**Issue by bifr0ns** [FancyGrid/FancyGrid#87]
I want to return the value before modifying the cell if **result.put("success", false)**, instead of leaving the cell with the new value if is not going to be added to the database anyway because it was false. This is all on the service.

Is there a way to do this?

**Comment by MikhailTatsky** [comment]
You can do the following.
There is `servererror`
https://fancygrid.com/api/events/servererror
You can return from server
`{"success": false}` 
Your server answer could contains details of update.
On case you do not want to return from server info of failed changes, you can 
take changes from `grid.store.changed`.

**Comment by bifr0ns** [comment]
Thanks, exactly what i was looking for.

**Comment by MikhailTatsky** [comment]
Glad to help.
