### ISSUE TITLE
horizontal overflow scroll bug on apple trackpad/magic mouse

### ISSUE THREAD

**Issue by 890f2151c2be69c51db72017546d00fd** [FancyGrid/FancyGrid#89]
Hi
when sum of columns width is bigger than table width then horizontal scrollbar appears. but when i try scroll to side (move fingers to side) on macbook trackpad or on magic mouse it doesnt work (it scrolls vertical instead of horizontal). when i drag and move with slider element it works correctly

example https://jsfiddle.net/wz7ojuda/

**Comment by MikhailTatsky** [comment]
Thank you for the report.
We will study it and fix.
