### ISSUE TITLE
How to clear the text in header filter field?

### ISSUE THREAD

**Issue by dreaming1402** [FancyGrid/FancyGrid#9]
When I call method grid.clearFilter(), the text in header field does not clear,
so, how to clear the text in header filer field?

**Comment by MikhailTatsky** [comment]
It was fixed in version 1.6.2, we will release it on next weekends.

**Comment by dreaming1402** [comment]
Thank you so much, I'm waiting... :dagger:

**Comment by MikhailTatsky** [comment]
You can download now next version here
https://code.fancygrid.com/fancygrid-next.zip

**Comment by dreaming1402** [comment]
Amazing :1st_place_medal:
I'm the 1st user :+1: 
Thank you so much
http://prntscr.com/fwlbgt
http://prntscr.com/fwlc0u

**Comment by MikhailTatsky** [comment]
;)

**Comment by dreaming1402** [comment]
Hello Mr MikhailTatsky,

To day I have a test with new version, the column combo it work fine when I call clearFilter(); method.
But someone like string, number it not working same, please checking again :+1:

**Comment by dreaming1402** [comment]
This is new error when I have 2 button like this
![image](https://user-images.githubusercontent.com/22629505/28416234-63138a4e-6d7d-11e7-9a74-504be0f12319.png)

this is my code:
![image](https://user-images.githubusercontent.com/22629505/28416321-b9d9e9a4-6d7d-11e7-9ab6-b1edd3a9f103.png)

By click on button 1, I get this error, button 2 it working fine
I'm try to run by o;d version 1.6.0, both button working fine

**Comment by MikhailTatsky** [comment]
Thank you for screenshot.
We already fixed it but we will release all on weekends - it needs time for tests.

**Comment by MikhailTatsky** [comment]
Please try again pre-release version.
https://code.fancygrid.com/fancygrid-next.zip
It contains:
- Fix for this bug
- getDataFiltered function
- Fix for issue https://github.com/FancyGrid/FancyGrid/issues/7
