### ISSUE TITLE
How to make a hbar stretched to the full width of the parent element?

### ISSUE THREAD

**Issue by ns16** [FancyGrid/FancyGrid#93]
This is my code:
```
<div id="hbar"></div>
```
```
const hbar = new Fancy.Grid({
  renderTo: 'hbar',
  theme: 'blue',
  width: 'fit',
  height: 'fit',
  cellHeight: 33,
  data: data,
  trackOver: true,
  selModel: 'row',
  defaults: {
	width: 100,
	resizable: true
  },
  columns: [
	{
	  title: 'Column 1',
	  index: 'col1',
	  width: 'fit'
	},
	{
	  type: 'hbar',
	  index: [
		'col2',
		'col3',
		'col4'
	  ],
	  width: 'fit',
	  sparkConfig: {
		tipFormat: (o) => {
		  return `${o.title} is ${o.value}`
		},
		title: [
		  'Column 2',
		  'Column 3',
		  'Column 4'
		],
		legend: {
		  type: 'bbar'
		}
	  }
	}
  ]
})
```
Now the hbar is stretched to the full width, but it is empty.
If to specify a fixed width for the hbar and its columns, the hbar is displayed correctly, but it does not stretch to the full width.

**Comment by MikhailTatsky** [comment]
Good day,
Thank you for your question.
Could modify this sample to your case, please?
https://jsfiddle.net/fancygrid/a1ev9ndc/
I did not get what exactly you need.

About 'fit' for columns, it works only for height and width of grid, not for columns.
I advice you to study `flex`.
https://fancygrid.com/api/config/columns/flex

**Comment by ns16** [comment]
I want the hbar to occupy the entire width of the parent element.
I also want the hbar and its columns to stretch and narrow when the browser window is resized.
I tried to do this by adding the flex property to the second column, but this does not work the way I expect.
https://jsfiddle.net/fancygrid/a1ev9ndc/

**Comment by MikhailTatsky** [comment]
I am afraid that I need some image/screenshot of final result.
I could not get the whole picture.
