### ISSUE TITLE
Summary row isn't updated correctly when a column is removed (deselect in column's menu)

### ISSUE THREAD

**Issue by tss008** [FancyGrid/FancyGrid#94]
I have a simple table with a summary row at the top. If any column is removed by using column's menu the summary row still has that column.

**Comment by MikhailTatsky** [comment]
@tss008 
 Thank you for reporting.
We will check and answer you shortly.

**Comment by MikhailTatsky** [comment]
It is bug.
We will try to do fix release on this weekend.

Thank you very much for reporting.

**Comment by MikhailTatsky** [comment]
Fixed.
