### ISSUE TITLE
Group on collapse event 

### ISSUE THREAD

**Issue by Roman9961** [FancyGrid/FancyGrid#95]
is it possible to listen open/close group?

**Comment by MikhailTatsky** [comment]
@Roman9961 
 Thank you for your questions.
There are not documented events for this case(we will add them in doc).
Here is how to use them 
```
events: [{
  expand: function(grid, group, groupValue) {

  }
}, {
  collapse: function(grid, group, groupValue) {

  }
}]
```

**Comment by Roman9961** [comment]
Thank you! for quick response.
