### ISSUE TITLE
fancygrid remove some object properties

### ISSUE THREAD

**Issue by Roman9961** [FancyGrid/FancyGrid#97]
I have array of objects provided to fancygrid:
![image](https://user-images.githubusercontent.com/22012446/54924243-9dfc2b00-4f14-11e9-8920-2efeb39a98f8.png)
but after initializing some field gone, I dump data provided to render function and that is what I have:
![image](https://user-images.githubusercontent.com/22012446/54924363-e3b8f380-4f14-11e9-8c30-5247d7e6a2ad.png)

**Comment by MikhailTatsky** [comment]
Do you mean in data?
If yes then define data properties, please.
Grid tries to read data from column indexes.
https://fancygrid.com/api/config/data/fields
Grid specially omits not used data properties.

**Comment by Roman9961** [comment]
I need some fields only for styling I didn't want to show it as column

**Comment by MikhailTatsky** [comment]
Yes, I see your point.
The matter grid take only used params, it is for perfomance.
If you need some extra data params than you need to define list of used params in property `indexes`.
It means that you do not need to define column with data index.
https://fancygrid.com/api/config/data/fields

**Comment by Roman9961** [comment]
Thank you, define fields explisitly helps )
